In [1]:
import json
import pandas as pd

In [2]:
df_lastfm = pd.read_json("../../data/raw/lastfm_scrobbles.json")

# Mantém apenas registros com data
df_lastfm = df_lastfm.dropna(subset=['date']).reset_index(drop=True)

df_lastfm.head(10)

,artist,streamable,image,mbid,album,name,url,date
0,{'mbid': 'e5712ceb-c37a-4c49-a11c-ccf4e21852d4...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",,{'mbid': 'ce866c52-d8b0-440a-af14-64fb9a1052a6...,FF,https://www.last.fm/music/Troye+Sivan/_/FF,"{'uts': '1792529089', '#text': '20 Oct 2026, 2..."
1,{'mbid': 'e5712ceb-c37a-4c49-a11c-ccf4e21852d4...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",,{'mbid': 'ce866c52-d8b0-440a-af14-64fb9a1052a6...,emBARRAssingly,https://www.last.fm/music/Troye+Sivan/_/emBARR...,"{'uts': '1792528877', '#text': '20 Oct 2026, 2..."
2,"{'mbid': '', '#text': 'Troye Sivan'}",0,"[{'size': 'small', '#text': 'https://lastfm-im...",,{'mbid': 'ce866c52-d8b0-440a-af14-64fb9a1052a6...,Lost Time (feat. Lily-Rose Depp),https://www.last.fm/music/Troye+Sivan/_/Lost+T...,"{'uts': '1792528636', '#text': '20 Oct 2026, 2..."
3,"{'mbid': '', '#text': 'Troye Sivan'}",0,"[{'size': 'small', '#text': 'https://lastfm-im...",,{'mbid': 'ce866c52-d8b0-440a-af14-64fb9a1052a6...,Lost Time (feat. Lily-Rose Depp),https://www.last.fm/music/Troye+Sivan/_/Lost+T...,"{'uts': '1792527854', '#text': '20 Oct 2026, 2..."
4,{'mbid': 'e5712ceb-c37a-4c49-a11c-ccf4e21852d4...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",,{'mbid': 'ce866c52-d8b0-440a-af14-64fb9a1052a6...,lOVE sO BIG IT hUrts,https://www.last.fm/music/Troye+Sivan/_/lOVE+s...,"{'uts': '1792527635', '#text': '20 Oct 2026, 2..."
5,{'mbid': 'e5712ceb-c37a-4c49-a11c-ccf4e21852d4...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",,{'mbid': 'ce866c52-d8b0-440a-af14-64fb9a1052a6...,FF,https://www.last.fm/music/Troye+Sivan/_/FF,"{'uts': '1792527089', '#text': '20 Oct 2026, 2..."
6,{'mbid': 'e5712ceb-c37a-4c49-a11c-ccf4e21852d4...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",,{'mbid': 'ce866c52-d8b0-440a-af14-64fb9a1052a6...,TROYE MEETs world,https://www.last.fm/music/Troye+Sivan/_/TROYE+...,"{'uts': '1792526925', '#text': '20 Oct 2026, 2..."
7,{'mbid': 'e5712ceb-c37a-4c49-a11c-ccf4e21852d4...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",,{'mbid': 'ce866c52-d8b0-440a-af14-64fb9a1052a6...,Sex Star,https://www.last.fm/music/Troye+Sivan/_/Sex+Star,"{'uts': '1792526737', '#text': '20 Oct 2026, 2..."
8,{'mbid': '2b1e7c27-2663-43df-9c23-8601e173e6ef...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",37db0d8f-1d5b-4dde-85f2-9df64d1173f0,{'mbid': 'a490743f-ed94-4d5f-976d-48612d25c80d...,Desmitificar,https://www.last.fm/music/Marina+Sena/_/Desmit...,"{'uts': '1792495747', '#text': '20 Oct 2026, 1..."
9,{'mbid': 'e5712ceb-c37a-4c49-a11c-ccf4e21852d4...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",,{'mbid': 'ce866c52-d8b0-440a-af14-64fb9a1052a6...,Le Boy,https://www.last.fm/music/Troye+Sivan/_/Le+Boy,"{'uts': '1792429263', '#text': '19 Oct 2026, 1..."

In [3]:
df_lastfm.shape

(1420, 8)

In [4]:
artist_normalizado = pd.json_normalize(df_lastfm['artist'])
album_normalizado = pd.json_normalize(df_lastfm['album'])
data_normalizado = pd.json_normalize(df_lastfm['date'])
df_lastfm['artist_name'] = artist_normalizado['#text']
df_lastfm['album_name'] = album_normalizado['#text']
df_lastfm['scrobble_date'] = data_normalizado['uts'] 
df_lastfm['music_name'] = df_lastfm['name']

# trocando a extração de text para uts -> timestamp unix que contabiliza as horas desde 00:00 1 de janeiro de 1970
df_lastfm['artist_mbid'] = df_lastfm['artist'].str['mbid'] #extraindo ID
df_lastfm.head()

,artist,streamable,image,mbid,album,name,url,date,artist_name,album_name,scrobble_date,music_name,artist_mbid
0,{'mbid': 'e5712ceb-c37a-4c49-a11c-ccf4e21852d4...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",,{'mbid': 'ce866c52-d8b0-440a-af14-64fb9a1052a6...,FF,https://www.last.fm/music/Troye+Sivan/_/FF,"{'uts': '1792529089', '#text': '20 Oct 2026, 2...",Troye Sivan,She’s the Best,1792529089,FF,e5712ceb-c37a-4c49-a11c-ccf4e21852d4
1,{'mbid': 'e5712ceb-c37a-4c49-a11c-ccf4e21852d4...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",,{'mbid': 'ce866c52-d8b0-440a-af14-64fb9a1052a6...,emBARRAssingly,https://www.last.fm/music/Troye+Sivan/_/emBARR...,"{'uts': '1792528877', '#text': '20 Oct 2026, 2...",Troye Sivan,She’s the Best,1792528877,emBARRAssingly,e5712ceb-c37a-4c49-a11c-ccf4e21852d4
2,"{'mbid': '', '#text': 'Troye Sivan'}",0,"[{'size': 'small', '#text': 'https://lastfm-im...",,{'mbid': 'ce866c52-d8b0-440a-af14-64fb9a1052a6...,Lost Time (feat. Lily-Rose Depp),https://www.last.fm/music/Troye+Sivan/_/Lost+T...,"{'uts': '1792528636', '#text': '20 Oct 2026, 2...",Troye Sivan,She’s the Best,1792528636,Lost Time (feat. Lily-Rose Depp),
3,"{'mbid': '', '#text': 'Troye Sivan'}",0,"[{'size': 'small', '#text': 'https://lastfm-im...",,{'mbid': 'ce866c52-d8b0-440a-af14-64fb9a1052a6...,Lost Time (feat. Lily-Rose Depp),https://www.last.fm/music/Troye+Sivan/_/Lost+T...,"{'uts': '1792527854', '#text': '20 Oct 2026, 2...",Troye Sivan,She’s the Best,1792527854,Lost Time (feat. Lily-Rose Depp),
4,{'mbid': 'e5712ceb-c37a-4c49-a11c-ccf4e21852d4...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",,{'mbid': 'ce866c52-d8b0-440a-af14-64fb9a1052a6...,lOVE sO BIG IT hUrts,https://www.last.fm/music/Troye+Sivan/_/lOVE+s...,"{'uts': '1792527635', '#text': '20 Oct 2026, 2...",Troye Sivan,She’s the Best,1792527635,lOVE sO BIG IT hUrts,e5712ceb-c37a-4c49-a11c-ccf4e21852d4

In [5]:
# Trata strings vazias como valores ausentes
df_lastfm["artist_mbid"] = df_lastfm["artist_mbid"].replace("", pd.NA)

# Para cada artista, reúne os IDs preenchidos, sem repetição
ids_por_artista = df_lastfm.groupby("artist_name")["artist_mbid"].agg(
    lambda coluna: coluna.dropna().unique()
)

# Só aproveita o ID quando existe exatamente um para aquele nome
mbid_por_artista = {
    artista: ids[0]
    for artista, ids in ids_por_artista.items()
    if len(ids) == 1
}

# Preenche apenas os valores ausentes
df_lastfm["artist_mbid"] = df_lastfm["artist_mbid"].fillna(
    df_lastfm["artist_name"].map(mbid_por_artista)
    #O .map(mbid_por_artista) procura cada nome de artista no dicionário e retorna o MBID correspondente.
)

In [6]:
df_lastfm.drop(columns=['name','image','artist','streamable','mbid','date','album','url'], inplace=True)

In [7]:
df_lastfm.head(10)

,artist_name,album_name,scrobble_date,music_name,artist_mbid
0,Troye Sivan,She’s the Best,1792529089,FF,e5712ceb-c37a-4c49-a11c-ccf4e21852d4
1,Troye Sivan,She’s the Best,1792528877,emBARRAssingly,e5712ceb-c37a-4c49-a11c-ccf4e21852d4
2,Troye Sivan,She’s the Best,1792528636,Lost Time (feat. Lily-Rose Depp),e5712ceb-c37a-4c49-a11c-ccf4e21852d4
3,Troye Sivan,She’s the Best,1792527854,Lost Time (feat. Lily-Rose Depp),e5712ceb-c37a-4c49-a11c-ccf4e21852d4
4,Troye Sivan,She’s the Best,1792527635,lOVE sO BIG IT hUrts,e5712ceb-c37a-4c49-a11c-ccf4e21852d4
5,Troye Sivan,She’s the Best,1792527089,FF,e5712ceb-c37a-4c49-a11c-ccf4e21852d4
6,Troye Sivan,She’s the Best,1792526925,TROYE MEETs world,e5712ceb-c37a-4c49-a11c-ccf4e21852d4
7,Troye Sivan,She’s the Best,1792526737,Sex Star,e5712ceb-c37a-4c49-a11c-ccf4e21852d4
8,Marina Sena,Coisas Naturais,1792495747,Desmitificar,2b1e7c27-2663-43df-9c23-8601e173e6ef
9,Troye Sivan,She’s the Best,1792429263,Le Boy,e5712ceb-c37a-4c49-a11c-ccf4e21852d4

In [8]:
df_lastfm.columns

Index(['artist_name', 'album_name', 'scrobble_date', 'music_name',
       'artist_mbid'],
      dtype='str')

In [9]:
print(df_lastfm['scrobble_date'].dtype)

str

In [10]:
df_lastfm['scrobble_date'] = df_lastfm['scrobble_date'].astype(int) #unit só lê int, e uts estava como str

In [11]:
#ajustes a serem feitos:
# Converter scrobble_date de texto pra um tipo datetime de verdade
# Ajustar o fuso horário de UTC pra Brasília (UTC-3)

df_lastfm['scrobble_date'] = pd.to_datetime(df_lastfm['scrobble_date'], unit='s', utc=True)
#unit='s' indica que o número indica segundos
#utc=True diz que essa data, assim que convertida, esta marcada como UTC -> padrão global para registrar datas e horas sem considerar fuso-horário
# primeiro passar para padrão (utc), depois passar para fuso de brasília

In [12]:
df_lastfm['scrobble_date'] = df_lastfm['scrobble_date'].dt.tz_convert('America/Sao_Paulo')
df_lastfm.head(10)

,artist_name,album_name,scrobble_date,music_name,artist_mbid
0,Troye Sivan,She’s the Best,2026-10-20 17:44:49-03:00,FF,e5712ceb-c37a-4c49-a11c-ccf4e21852d4
1,Troye Sivan,She’s the Best,2026-10-20 17:41:17-03:00,emBARRAssingly,e5712ceb-c37a-4c49-a11c-ccf4e21852d4
2,Troye Sivan,She’s the Best,2026-10-20 17:37:16-03:00,Lost Time (feat. Lily-Rose Depp),e5712ceb-c37a-4c49-a11c-ccf4e21852d4
3,Troye Sivan,She’s the Best,2026-10-20 17:24:14-03:00,Lost Time (feat. Lily-Rose Depp),e5712ceb-c37a-4c49-a11c-ccf4e21852d4
4,Troye Sivan,She’s the Best,2026-10-20 17:20:35-03:00,lOVE sO BIG IT hUrts,e5712ceb-c37a-4c49-a11c-ccf4e21852d4
5,Troye Sivan,She’s the Best,2026-10-20 17:11:29-03:00,FF,e5712ceb-c37a-4c49-a11c-ccf4e21852d4
6,Troye Sivan,She’s the Best,2026-10-20 17:08:45-03:00,TROYE MEETs world,e5712ceb-c37a-4c49-a11c-ccf4e21852d4
7,Troye Sivan,She’s the Best,2026-10-20 17:05:37-03:00,Sex Star,e5712ceb-c37a-4c49-a11c-ccf4e21852d4
8,Marina Sena,Coisas Naturais,2026-10-20 08:29:07-03:00,Desmitificar,2b1e7c27-2663-43df-9c23-8601e173e6ef
9,Troye Sivan,She’s the Best,2026-10-19 14:01:03-03:00,Le Boy,e5712ceb-c37a-4c49-a11c-ccf4e21852d4

In [13]:
df_lastfm['date'] = df_lastfm['scrobble_date'].dt.date
df_lastfm['time'] = df_lastfm['scrobble_date'].dt.time
df_lastfm['week_day'] = df_lastfm['scrobble_date'].dt.day_name()
df_lastfm['week_day_id'] = df_lastfm['scrobble_date'].dt.dayofweek
df_lastfm['group_hour'] = df_lastfm['scrobble_date'].dt.hour
# melhor para fazer agrupamento dos tempos, pois cada tempo é diferente -> mais difícil para análise

df_lastfm.head(10)

#mantém scroble_date para comparações mais fáceis de serem feitas que os dados separados

,artist_name,album_name,scrobble_date,music_name,artist_mbid,date,time,week_day,week_day_id,group_hour
0,Troye Sivan,She’s the Best,2026-10-20 17:44:49-03:00,FF,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-20,17:44:49,Tuesday,1,17
1,Troye Sivan,She’s the Best,2026-10-20 17:41:17-03:00,emBARRAssingly,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-20,17:41:17,Tuesday,1,17
2,Troye Sivan,She’s the Best,2026-10-20 17:37:16-03:00,Lost Time (feat. Lily-Rose Depp),e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-20,17:37:16,Tuesday,1,17
3,Troye Sivan,She’s the Best,2026-10-20 17:24:14-03:00,Lost Time (feat. Lily-Rose Depp),e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-20,17:24:14,Tuesday,1,17
4,Troye Sivan,She’s the Best,2026-10-20 17:20:35-03:00,lOVE sO BIG IT hUrts,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-20,17:20:35,Tuesday,1,17
5,Troye Sivan,She’s the Best,2026-10-20 17:11:29-03:00,FF,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-20,17:11:29,Tuesday,1,17
6,Troye Sivan,She’s the Best,2026-10-20 17:08:45-03:00,TROYE MEETs world,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-20,17:08:45,Tuesday,1,17
7,Troye Sivan,She’s the Best,2026-10-20 17:05:37-03:00,Sex Star,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-20,17:05:37,Tuesday,1,17
8,Marina Sena,Coisas Naturais,2026-10-20 08:29:07-03:00,Desmitificar,2b1e7c27-2663-43df-9c23-8601e173e6ef,2026-10-20,08:29:07,Tuesday,1,8
9,Troye Sivan,She’s the Best,2026-10-19 14:01:03-03:00,Le Boy,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-19,14:01:03,Monday,0,14

In [14]:
df_lastfm.to_csv('../../data/processed/lastfm_transformed.csv', index=False)