In [48]:
import pandas as pd

In [49]:
df_lastfm = pd.read_csv('../../data/processed/lastfm_transformed.csv')
df_lastfm.head(10)

,artist_name,album_name,scrobble_date,music_name,artist_mbid,date,time,week_day,week_day_id,group_hour
0,ADÉLA,Ain't In LA,2026-10-08 07:48:52-03:00,Ain't In LA,f40856e6-079f-4a0a-916e-9e6a5e04f646,2026-10-08,07:48:52,Thursday,3,7
1,Kersty,ELECTRONS,2026-10-08 07:45:26-03:00,ELECTRONS,NaN,2026-10-08,07:45:26,Thursday,3,7
2,Troye Sivan,Bloom,2026-10-08 07:41:57-03:00,Lucky Strike,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-08,07:41:57,Thursday,3,7
3,Olivia Rodrigo,you seem pretty sad for a girl so in love,2026-10-08 07:37:53-03:00,purple,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-08,07:37:53,Thursday,3,7
4,Gal Costa,Mina D'água do meu Canto,2026-10-08 07:34:15-03:00,Morena Dos Olhos D'agua,fc63a914-272d-4b95-9221-61adcce6f793,2026-10-08,07:34:15,Thursday,3,7
5,Evan,DEATH OF ME,2026-10-08 07:31:08-03:00,Death of Me,fcc72364-27ff-4c1b-aea3-bc41449003b6,2026-10-08,07:31:08,Thursday,3,7
6,Troye Sivan,Bloom,2026-10-08 07:26:39-03:00,The Good Side,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-08,07:26:39,Thursday,3,7
7,XG,AWE,2026-10-08 07:23:45-03:00,IS THIS LOVE,8dfe067c-ae90-472e-80f2-fcee9be4e158,2026-10-08,07:23:45,Thursday,3,7
8,ADÉLA,PRIMA,2026-10-08 07:21:14-03:00,I'M THE MAN,f40856e6-079f-4a0a-916e-9e6a5e04f646,2026-10-08,07:21:14,Thursday,3,7
9,Troye Sivan,In a Dream,2026-10-08 07:17:24-03:00,IN A DREAM,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-08,07:17:24,Thursday,3,7

In [50]:
df_mb= pd.read_csv('../../data/processed/musicBrainz_transformed.csv')

In [51]:
print(df_lastfm.columns.tolist())

['artist_name', 'album_name', 'scrobble_date', 'music_name', 'artist_mbid', 'date', 'time', 'week_day', 'week_day_id', 'group_hour']

In [52]:
print(df_mb.columns.tolist())

['id', 'type', 'name', 'gender', 'country', 'area.type', 'area.name', 'query_name', 'legal_name', 'music_genre']

In [53]:
# Padroniza os nomes: remove espaços nas pontas e converte para minúsculas
df_lastfm['nome_chave'] = df_lastfm['artist_name'].str.strip().str.lower()
df_mb['nome_chave'] = df_mb['query_name'].str.strip().str.lower()
# padroniza nomes de artistas ex: willow, que no musicBrainz aparecia como WILLOW

# Mantém todas as linhas da tabela Last.fm
df_final = df_lastfm.merge(
    df_mb,
    on='nome_chave',
    how='left'
)

# Remove a coluna auxiliar do resultado
df_final = df_final.drop(columns=['nome_chave'])
# query_name é a "ponte" garantida entre as duas tabelas, porque ela nasceu do mesmo valor original.

In [54]:
# df_final = df_lastfm.merge(df_mb, left_on='artist_name', right_on='name', how='left')
# #last_fm -> tabela base
# #left_on= tabela da esquerda e chave de comparação
# #right_on= tabela da direita + chave de comparação
# #how=left -> mantem todas as linhas da tabela principal mesmo que não haja relação com a outra tabela

In [55]:
df_final.head(50)

,artist_name,album_name,scrobble_date,music_name,artist_mbid,date,time,week_day,week_day_id,group_hour,id,type,name,gender,country,area.type,area.name,query_name,legal_name,music_genre
0,ADÉLA,Ain't In LA,2026-10-08 07:48:52-03:00,Ain't In LA,f40856e6-079f-4a0a-916e-9e6a5e04f646,2026-10-08,07:48:52,Thursday,3,7,f40856e6-079f-4a0a-916e-9e6a5e04f646,Artist name,ADÉLA,female,SK,Country,Slovakia,ADÉLA,Adéla Jergová,electronic
1,Kersty,ELECTRONS,2026-10-08 07:45:26-03:00,ELECTRONS,NaN,2026-10-08,07:45:26,Thursday,3,7,5925e68f-721d-444e-afe4-32dd019c45c2,unregistered,Kersty Ryan,unregistered,unregistered,unregistered,unregistered,Kersty,unregistered,unregistered
2,Troye Sivan,Bloom,2026-10-08 07:41:57-03:00,Lucky Strike,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-08,07:41:57,Thursday,3,7,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,Artist name,Troye Sivan,male,AU,Country,Australia,Troye Sivan,Troye Sivan Mellet,synthpop
3,Olivia Rodrigo,you seem pretty sad for a girl so in love,2026-10-08 07:37:53-03:00,purple,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-08,07:37:53,Thursday,3,7,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Artist name,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,Olivia Isabel Rodrigo,rock
4,Gal Costa,Mina D'água do meu Canto,2026-10-08 07:34:15-03:00,Morena Dos Olhos D'agua,fc63a914-272d-4b95-9221-61adcce6f793,2026-10-08,07:34:15,Thursday,3,7,fc63a914-272d-4b95-9221-61adcce6f793,Artist name,Gal Costa,female,BR,Country,Brazil,Gal Costa,Maria da Graça Costa Penna Burgos,mpb
5,Evan,DEATH OF ME,2026-10-08 07:31:08-03:00,Death of Me,fcc72364-27ff-4c1b-aea3-bc41449003b6,2026-10-08,07:31:08,Thursday,3,7,751adfe4-6e40-4ab4-866c-ed14f5087d76,Artist name,Evan Call,male,JP,Country,Japan,Evan,unregistered,anime
6,Troye Sivan,Bloom,2026-10-08 07:26:39-03:00,The Good Side,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-08,07:26:39,Thursday,3,7,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,Artist name,Troye Sivan,male,AU,Country,Australia,Troye Sivan,Troye Sivan Mellet,synthpop
7,XG,AWE,2026-10-08 07:23:45-03:00,IS THIS LOVE,8dfe067c-ae90-472e-80f2-fcee9be4e158,2026-10-08,07:23:45,Thursday,3,7,8dfe067c-ae90-472e-80f2-fcee9be4e158,Artist name,XG,unregistered,KR,Country,South Korea,XG,unregistered,pop
8,ADÉLA,PRIMA,2026-10-08 07:21:14-03:00,I'M THE MAN,f40856e6-079f-4a0a-916e-9e6a5e04f646,2026-10-08,07:21:14,Thursday,3,7,f40856e6-079f-4a0a-916e-9e6a5e04f646,Artist name,ADÉLA,female,SK,Country,Slovakia,ADÉLA,Adéla Jergová,electronic
9,Troye Sivan,In a Dream,2026-10-08 07:17:24-03:00,IN A DREAM,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-08,07:17:24,Thursday,3,7,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,Artist name,Troye Sivan,male,AU,Country,Australia,Troye Sivan,Troye Sivan Mellet,synthpop
10,ADÉLA,PRIMA,2026-10-08 07:15:27-03:00,Marijuana,f40856e6-079f-4a0a-916e-9e6a5e04f646,2026-10-08,07:15:27,Thursday,3,7,f40856e6-079f-4a0a-916e-9e6a5e04f646,Artist name,ADÉLA,female,SK,Country,Slovakia,ADÉLA,Adéla Jergová,electronic
11,Troye Sivan,Spotify Singles,2026-10-08 07:11:45-03:00,Bloom - Recorded At Spotify Studios NYC,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-08,07:11:45,Thursday,3,7,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,Artist name,Troye Sivan,male,AU,Country,Australia,Troye Sivan,Troye Sivan Mellet,synthpop
12,Troye Sivan,In a Dream,2026-10-08 07:07:27-03:00,Take Yourself Home,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-08,07:07:27,Thursday,3,7,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,Artist name,Troye Sivan,male,AU,Country,Australia,Troye Sivan,Troye Sivan Mellet,synthpop
13,t.A.T.u.,200 KM/H In The Wrong Lane (10th Anniversary E...,2026-10-08 07:03:46-03:00,All the Things She Said,7c20f558-d664-42bd-b6f1-81acf9dbb72d,2026-10-08,07:03:46,Thursday,3,7,7c20f558-d664-42bd-b6f1-81acf9dbb72d,Artist name,t.A.T.u.,unregistered,RU,Country,Russia,t.A.T.u.,unregistered,rock
14,Olivia Rodrigo,you seem pretty sad for a girl so in love,2026-10-08 06:59:45-03:00,maggots for brains,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-08,06:59:45,Thursday,3,6,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Artist name,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,Olivia Isabel Rodrigo,rock
15,Olivia Rodrigo,Serena Joy,2026-10-08 06:56:23-03:00,serena joy,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-08,06:56:23,Thursday,3,6,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Artist name,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,Olivia Isabel Rodrigo,rock
16,ADÉLA,PRIMA,2026-10-08 06:52:52-03:00,NICOLE KIDMAN,f40856e6-079f-4a0a-916e-9e6a5e04f646,2026-10-08,06:52:52,Thursday,3,6,f40856e6-079f-4a0a-916e-9e6a5e04f646,Artist name,ADÉLA,female,SK,Country,Slovakia,ADÉLA,Adéla Jergová,electronic
17,George Michael,Ladies & Gentlemen,2026-10-08 06:45:37-03:00,Cowboys And Angels - 2010 Remastered Version,ccb8f30e-4d71-40c4-8b1d-846dafe73e2c,2026-10-08,06:45:37,Thursday,3,6,ccb8f30e-4d71-40c4-8b1d-846dafe73e2c,unregistered,George Michael,male,GB,Country,United Kingdom,George Michael,Georgios Kyriacos Panayiotou,rock
18,Sabrina Carpenter,Man’s Best Friend,2026-10-08 06:42:31-03:00,Sugar Talking,1882fe91-cdd9-49c9-9956-8e06a3810bd4,2026-10-08,06:42:31,Thursday,3,6,1882fe91-cdd9-49c9-9956-8e06a3810bd4,Artist name,Sabrina Carpenter,female,US,Country,United States,Sabrina Carpenter,Sabrina Annlynn Carpenter,pop
19,O Rappa,Nunca Tem Fim (Standard),2026-10-08 06:17:54-03:00,Anjos (Pra Quem Tem Fé),00034ede-a1f1-4219-be39-02f36853373e,2026-10-08,06:17:54,Thursday,3,6,00034ede-a1f1-4219-be39-02f36853373e,unregistered,O Rappa,unregistered,BR,Country,Brazil,O Rappa,unregistered,alternative rock
20,George Michael,Ladies & Gentlemen,2026-10-08 03:12:31-03:00,Cowboys And Angels - 2010 Remastered Version,ccb8f30e-4d71-40c4-8b1d-846dafe73e2c,2026-10-08,03:12:31,Thursday,3,3,ccb8f30e-4d71-40c4-8b1d-846dafe73e2c,unregistered,George Michael,male,GB,Country,United Kingdom,George Michael,Georgios Kyriacos Panayiotou,rock
21,George Michael,Ladies & Gentlemen,2026-10-07 21:10:59-03:00,Cowboys And Angels - 2010 Remastered Version,ccb8f30e-4d71-40c4-8b1d-846dafe73e2c,2026-10-07,21:10:59,Wednesday,2,21,ccb8f30e-4d71-40c4-8b1d-846dafe73e2c,unregistered,George Michael,male,GB,Country,United Kingdom,George Michael,Georgios Kyriacos Panayiotou,rock
22,Secos & Molhados,A Volta De Secos & Molhados,2026-10-07 19:01:56-03:00,Sangue Latino,6840dcbe-3aca-4057-8d16-4799c3730e3a,2026-10-07,19:01:56,Wednesday,2,19,6840dcbe-3aca-4057-8d16-4799c3730e3a,unregistered,Secos & Molhados,unregistered,BR,Country,Brazil,Secos & Molhados,unregistered,glam rock
23,Sabrina Carpenter,Man’s Best Friend,2026-10-07 18:56:51-03:00,Sugar Talking,1882fe91-cdd9-49c9-9956-8e06a3810bd4,2026-10-07,18:56:51,Wednesday,2,18,1882fe91-cdd9-49c9-9956-8e06a3810bd4,Artist name,Sabrina Carpenter,female,US,Country,United States,Sabrina Carpenter,Sabrina Annlynn Carpenter,pop
24,Olivia Rodrigo,you seem pretty sad for a girl so in love,2026-10-07 18:52:59-03:00,honeybee,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-07,18:52:59,Wednesday,2,18,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Artist name,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,Olivia Isabel Rodrigo,rock
25,George Michael,Ladies & Gentlemen,2026-10-06 20:17:06-03:00,Cowboys And Angels - 2010 Remastered Version,ccb8f30e-4d71-40c4-8b1d-846dafe73e2c,2026-10-06,20:17:06,Tuesday,1,20,ccb8f30e-4d71-40c4-8b1d-846dafe73e2c,unregistered,George Michael,male,GB,Country,United Kingdom,George Michael,Georgios Kyriacos Panayiotou,rock
26,Sabrina Carpenter,Man’s Best Friend,2026-10-06 20:14:02-03:00,Sugar Talking,1882fe91-cdd9-49c9-9956-8e06a3810bd4,2026-10-06,20:14:02,Tuesday,1,20,1882fe91-cdd9-49c9-9956-8e06a3810bd4,Artist name,Sabrina Carpenter,female,US,Country,United States,Sabrina Carpenter,Sabrina Annlynn Carpenter,pop
27,ADÉLA,PRIMA,2026-10-06 20:13:52-03:00,I'M THE MAN,f40856e6-079f-4a0a-916e-9e6a5e04f646,2026-10-06,20:13:52,Tuesday,1,20,f40856e6-079f-4a0a-916e-9e6a5e04f646,Artist name,ADÉLA,female,SK,Country,Slovakia,ADÉLA,Adéla Jergová,electronic
28,t.A.T.u.,200 KM/H In The Wrong Lane (10th Anniversary E...,2026-10-06 18:04:35-03:00,All the Things She Said,7c20f558-d664-42bd-b6f1-81acf9dbb72d,2026-10-06,18:04:35,Tuesday,1,18,7c20f558-d664-42bd-b6f1-81acf9dbb72d,Artist name,t.A.T.u.,unregistered,RU,Country,Russia,t.A.T.u.,unregistered,rock
29,t.A.T.u.,200 KM/H In The Wrong Lane (10th Anniversary E...,2026-10-06 18:01:02-03:00,All the Things She Said,7c20f558-d664-42bd-b6f1-81acf9dbb72d,2026-10-06,18:01:02,Tuesday,1,18,7c20f558-d664-42bd-b6f1-81acf9dbb72d,Artist name,t.A.T.u.,unregistered,RU,Country,Russia,t.A.T.u.,unregistered,rock
30,t.A.T.u.,200 KM/H In The Wrong Lane (10th Anniversary E...,2026-10-06 17:57:12-03:00,All the Things She Said,7c20f558-d664-42bd-b6f1-81acf9dbb72d,2026-10-06,17:57:12,Tuesday,1,17,7c20f558-d664-42bd-b6f1-81acf9dbb72d,Artist name,t.A.T.u.,unregistered,RU,Country,Russia,t.A.T.u.,unregistered,rock
31,Madonna,Bedtime Stories,2026-10-06 17:51:31-03:00,Human Nature,79239441-bfd5-4981-a70c-55c3f15c1287,2026-10-06,17:51:31,Tuesday,1,17,79239441-bfd5-4981-a70c-55c3f15c1287,Artist name,Madonna,female,US,Country,United States,Madonna,Madonna Louise Veronica Ciccone,electronic
32,Olivia Rodrigo,Serena Joy,2026-10-06 17:39:33-03:00,serena joy,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-06,17:39:33,Tuesday,1,17,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Artist name,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,Olivia Isabel Rodrigo,rock
33,Olivia Rodrigo,Serena Joy,2026-10-06 17:35:02-03:00,serena joy,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-06,17:35:02,Tuesday,1,17,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Artist name,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,Olivia Isabel Rodrigo,rock
34,Olivia Rodrigo,Serena Joy,2026-10-06 17:31:19-03:00,serena joy,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-06,17:31:19,Tuesday,1,17,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Artist name,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,Olivia Isabel Rodrigo,rock
35,Olivia Rodrigo,Serena Joy,2026-10-06 17:28:06-03:00,serena joy,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-06,17:28:06,Tuesday,1,17,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Artist name,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,Olivia Isabel Rodrigo,rock
36,Chico Buarque,Chico Buarque,2026-10-06 17:08:49-03:00,Apesar de você,3a5d1cc7-627e-48ea-aba3-fdd20d782c33,2026-10-06,17:08:49,Tuesday,1,17,3a5d1cc7-627e-48ea-aba3-fdd20d782c33,Artist name,Chico Buarque,male,BR,Country,Brazil,Chico Buarque,Francisco Buarque de Hollanda,portuguese
37,Rita Lee,Rita Hits,2026-10-06 17:06:48-03:00,Lança Perfume,3f962bf0-42a0-45a0-830f-07b66301d35f,2026-10-06,17:06:48,Tuesday,1,17,3f962bf0-42a0-45a0-830f-07b66301d35f,Legal name,Rita Lee,female,BR,Country,Brazil,Rita Lee,Rita Lee Jones Carvalho,rock
38,Secos & Molhados,A Volta De Secos & Molhados,2026-10-06 15:55:18-03:00,Sangue Latino,6840dcbe-3aca-4057-8d16-4799c3730e3a,2026-10-06,15:55:18,Tuesday,1,15,6840dcbe-3aca-4057-8d16-4799c3730e3a,unregistered,Secos & Molhados,unregistered,BR,Country,Brazil,Secos & Molhados,unregistered,glam rock
39,O Rappa,Nunca Tem Fim (Standard),2026-10-06 06:17:26-03:00,Anjos (Pra Quem Tem Fé),00034ede-a1f1-4219-be39-02f36853373e,2026-10-06,06:17:26,Tuesday,1,6,00034ede-a1f1-4219-be39-02f36853373e,unregistered,O Rappa,unregistered,BR,Country,Brazil,O Rappa,unregistered,alternative rock
40,Chico Science,Afrociberdelia,2026-10-06 06:15:42-03:00,O Cidadão Do Mundo,NaN,2026-10-06,06:15:42,Tuesday,1,6,d4b0112d-f8aa-4880-a6c3-ab0ea94943a9,Legal name,Chico Science,male,BR,Country,Brazil,Chico Science,Francisco de Assis França,unregistered
41,O Rappa,Nunca Tem Fim (Standard),2026-10-06 06:08:43-03:00,Anjos (Pra Quem Tem Fé),00034ede-a1f1-4219-be39-02f36853373e,2026-10-06,06:08:43,Tuesday,1,6,00034ede-a1f1-4219-be39-02f36853373e,unregistered,O Rappa,unregistered,BR,Country,Brazil,O Rappa,unregistered,alternative rock
42,Ivete Sangalo,As Super Novas,2026-10-05 22:01:55-03:00,Quando a Chuva Passar,d553e89c-3c2a-4f10-9ce1-9eaa74de0129,2026-10-05,22:01:55,Monday,0,22,d553e89c-3c2a-4f10-9ce1-9eaa74de0129,unregistered,Ivete Sangalo,female,BR,Country,Brazil,Ivete Sangalo,Ivete Maria Dias de Sangalo Cady,singer-songwriter
43,Preta Gil,Prét-A-Porter,2026-10-05 21:57:24-03:00,Sinais de fogo,6348666a-b266-49d7-836c-b9d4741ba646,2026-10-05,21:57:24,Monday,0,21,6348666a-b266-49d7-836c-b9d4741ba646,Legal name,Preta Gil,female,BR,Country,Brazil,Preta Gil,Preta Maria Gadelha Gil Moreira,pop
44,Jorge Vercillo,Jorge Vercilo Ao Vivo,2026-10-05 21:47:47-03:00,Melhor Lugar - Ao Vivo No Rio De Janeiro / 2006,NaN,2026-10-05,21:47:47,Monday,0,21,9eb42a57-60f8-4093-a45d-1d882bdc7b8c,Artist name,Jorge Vercillo,male,BR,Country,Brazil,Jorge Vercillo,Jorge Luiz Sant'anna Vercillo,pop
45,Rita Lee,Saúde,2026-10-05 21:32:30-03:00,Mutante,3f962bf0-42a0-45a0-830f-07b66301d35f,2026-10-05,21:32:30,Monday,0,21,3f962bf0-42a0-45a0-830f-07b66301d35f,Legal name,Rita Lee,female,BR,Country,Brazil,Rita Lee,Rita Lee Jones Carvalho,rock
46,Rita Lee,Flerte Fatal,2026-10-05 21:28:25-03:00,Pega Rapaz,3f962bf0-42a0-45a0-830f-07b66301d35f,2026-10-05,21:28:25,Monday,0,21,3f962bf0-42a0-45a0-830f-07b66301d35f,Legal name,Rita Lee,female,BR,Country,Brazil,Rita Lee,Rita Lee Jones Carvalho,rock
47,Djavan,Djavan,2026-10-05 21:23:28-03:00,Oceano,751e517d-9663-4692-8c20-942e16d484c5,2026-10-05,21:23:28,Monday,0,21,751e517d-9663-4692-8c20-942e16d484c5,Legal name,Djavan,male,BR,Country,Brazil,Djavan,Djavan Caetano Viana,singer-songwriter
48,Marisa Monte,Infinito Particular,2026-10-05 21:19:58-03:00,Vilarejo,f81f19b9-c76e-43ac-8656-bb56071785fb,2026-10-05,21:19:58,Monday,0,21,f81f19b9-c76e-43ac-8656-bb56071785fb,Legal name,Marisa Monte,female,BR,Country,Brazil,Marisa Monte,Marisa de Azevedo Monte,singer-songwriter
49,Chico Buarque,Carioca ao Vivo (Ao Vivo),2026-10-05 18:39:14-03:00,João E Maria,3a5d1cc7-627e-48ea-aba3-fdd20d782c33,2026-10-05,18:39:14,Monday,0,18,3a5d1cc7-627e-48ea-aba3-fdd20d782c33,Artist name,Chico Buarque,male,BR,Country,Brazil,Chico Buarque,Francisco Buarque de Hollanda,portuguese

In [56]:
# colunas_mb = [
#     'id', 'type', 'name', 'gender', 'country',
#     'area.type', 'area.name', 'legal_name', 'music_genre'
# ]

# df_final[colunas_mb] = df_final[colunas_mb].fillna('unregistered')

In [57]:
df_final.isna().sum()

artist_name        0
album_name         0
scrobble_date      0
music_name         0
artist_mbid      120
date               0
time               0
week_day           0
week_day_id        0
group_hour         0
id                 4
type               4
name               4
gender             4
country            4
area.type          4
area.name          4
query_name         4
legal_name         4
music_genre        4
dtype: int64

In [58]:
df_final[df_final['artist_mbid'].isna()]

,artist_name,album_name,scrobble_date,music_name,artist_mbid,date,time,week_day,week_day_id,group_hour,id,type,name,gender,country,area.type,area.name,query_name,legal_name,music_genre
1,Kersty,ELECTRONS,2026-10-08 07:45:26-03:00,ELECTRONS,NaN,2026-10-08,07:45:26,Thursday,3,7,5925e68f-721d-444e-afe4-32dd019c45c2,unregistered,Kersty Ryan,unregistered,unregistered,unregistered,unregistered,Kersty,unregistered,unregistered
40,Chico Science,Afrociberdelia,2026-10-06 06:15:42-03:00,O Cidadão Do Mundo,NaN,2026-10-06,06:15:42,Tuesday,1,6,d4b0112d-f8aa-4880-a6c3-ab0ea94943a9,Legal name,Chico Science,male,BR,Country,Brazil,Chico Science,Francisco de Assis França,unregistered
44,Jorge Vercillo,Jorge Vercilo Ao Vivo,2026-10-05 21:47:47-03:00,Melhor Lugar - Ao Vivo No Rio De Janeiro / 2006,NaN,2026-10-05,21:47:47,Monday,0,21,9eb42a57-60f8-4093-a45d-1d882bdc7b8c,Artist name,Jorge Vercillo,male,BR,Country,Brazil,Jorge Vercillo,Jorge Luiz Sant'anna Vercillo,pop
62,Musa do Calypso,Musa do Calypso,2026-10-04 17:03:39-03:00,Podem Até Nos Separar,NaN,2026-10-04,17:03:39,Sunday,6,17,0c6a9b96-31d0-4be3-9b3e-eef6fdac9716,unregistered,Companhia do Calypso,unregistered,unregistered,unregistered,unregistered,Musa do Calypso,unregistered,unregistered
72,Beth Carvalho,A Madrinha Do Samba Ao Vivo Convida,2026-10-04 16:30:23-03:00,Água de Chuva No Mar - Ao Vivo,NaN,2026-10-04,16:30:23,Sunday,6,16,02809fda-8319-4628-b165-a51213bf30ac,Legal name,Beth Carvalho,female,BR,Country,Brazil,Beth Carvalho,Elizabeth Santos Leal de Carvalho,mpb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1087,Jennie,FALLEN ANGEL,2026-09-14 13:32:16-03:00,Fallen Angel,NaN,2026-09-14,13:32:16,Monday,0,13,779351de-0da5-4943-928b-495a3c40e8c0,Artist name,JENNIE,female,KR,Country,South Korea,Jennie,김제니,rock
1089,Kersty,ELECTRONS,2026-09-14 13:25:45-03:00,ELECTRONS,NaN,2026-09-14,13:25:45,Monday,0,13,5925e68f-721d-444e-afe4-32dd019c45c2,unregistered,Kersty Ryan,unregistered,unregistered,unregistered,unregistered,Kersty,unregistered,unregistered
1094,Kersty,ELECTRONS,2026-09-12 10:41:22-03:00,ELECTRONS,NaN,2026-09-12,10:41:22,Saturday,5,10,5925e68f-721d-444e-afe4-32dd019c45c2,unregistered,Kersty Ryan,unregistered,unregistered,unregistered,unregistered,Kersty,unregistered,unregistered
1119,Miley Cyrus,Can't Be Tamed,2026-09-10 14:08:55-03:00,Who Owns My Heart,NaN,2026-09-10,14:08:55,Thursday,3,14,7e9bd05a-117f-4cce-87bc-e011527a8b18,Artist name,Miley Cyrus,non-binary,US,Country,United States,Miley Cyrus,Miley Ray Cyrus,rock
1147,Adele,21,2026-09-06 19:20:21-03:00,Lovesong,NaN,2026-09-06,19:20:21,Sunday,6,19,cc2c9c3c-b7bc-4b8b-84d8-4fbd8779e493,Search hint,Adele,female,GB,Country,United Kingdom,Adele,Adele Adkins,pop

In [59]:
# sem_match = df_final[df_final['id'].isna()]['artist_name'].unique()
# print(sem_match)

In [60]:
df_final['artist_mbid'] = df_final['artist_mbid'].fillna('unregistered')

In [61]:
df_final.isna().sum()

artist_name      0
album_name       0
scrobble_date    0
music_name       0
artist_mbid      0
date             0
time             0
week_day         0
week_day_id      0
group_hour       0
id               4
type             4
name             4
gender           4
country          4
area.type        4
area.name        4
query_name       4
legal_name       4
music_genre      4
dtype: int64

In [62]:
df_final['id'] = df_final['id'].fillna('0')
df_final['type'] = df_final['type'].fillna('unregistered')
df_final['name'] = df_final['name'].fillna('unregistered')
df_final['gender'] = df_final['gender'].fillna('unregistered')
df_final['country'] = df_final['country'].fillna('unregistered')
df_final['area.type'] = df_final['area.type'].fillna('unregistered')
df_final['area.name'] = df_final['area.name'].fillna('unregistered')
df_final['query_name'] = df_final['query_name'].fillna('unregistered')
df_final['legal_name'] = df_final['legal_name'].fillna('unregistered')
df_final['music_genre'] = df_final['music_genre'].fillna('unregistered')

In [63]:
df_final.head(4)

,artist_name,album_name,scrobble_date,music_name,artist_mbid,date,time,week_day,week_day_id,group_hour,id,type,name,gender,country,area.type,area.name,query_name,legal_name,music_genre
0,ADÉLA,Ain't In LA,2026-10-08 07:48:52-03:00,Ain't In LA,f40856e6-079f-4a0a-916e-9e6a5e04f646,2026-10-08,07:48:52,Thursday,3,7,f40856e6-079f-4a0a-916e-9e6a5e04f646,Artist name,ADÉLA,female,SK,Country,Slovakia,ADÉLA,Adéla Jergová,electronic
1,Kersty,ELECTRONS,2026-10-08 07:45:26-03:00,ELECTRONS,unregistered,2026-10-08,07:45:26,Thursday,3,7,5925e68f-721d-444e-afe4-32dd019c45c2,unregistered,Kersty Ryan,unregistered,unregistered,unregistered,unregistered,Kersty,unregistered,unregistered
2,Troye Sivan,Bloom,2026-10-08 07:41:57-03:00,Lucky Strike,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-08,07:41:57,Thursday,3,7,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,Artist name,Troye Sivan,male,AU,Country,Australia,Troye Sivan,Troye Sivan Mellet,synthpop
3,Olivia Rodrigo,you seem pretty sad for a girl so in love,2026-10-08 07:37:53-03:00,purple,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-08,07:37:53,Thursday,3,7,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Artist name,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,Olivia Isabel Rodrigo,rock

In [66]:
df_final.isna().sum()

artist_name      0
album_name       0
scrobble_date    0
music_name       0
artist_mbid      0
date             0
time             0
week_day         0
week_day_id      0
group_hour       0
id               0
type             0
name             0
gender           0
country          0
area.type        0
area.name        0
query_name       0
legal_name       0
music_genre      0
dtype: int64