<span style="color:red; font-family:Helvetica Neue, Helvetica, Arial, sans-serif; font-size:2em;">An Exception was encountered at '<a href="#papermill-error-cell">In [16]</a>'.</span>

In [95]:
import pandas as pd

In [96]:
df_lastfm = pd.read_csv('../../data/processed/lastfm_transformed.csv')
df_lastfm.head(10)

,artist_name,album_name,scrobble_date,music_name,artist_mbid,date,time,week_day,week_day_id,group_hour
0,BTS,The Most Beautiful Moment in Life: Young Forever,2026-10-14 13:17:12-03:00,Converse High,0d79fe8e-ba27-4859-bb8c-2f255f346853,2026-10-14,13:17:12,Wednesday,2,13
1,RM,Indigo,2026-10-14 13:13:57-03:00,No.2 (with parkjiyoon),3be217fb-2b91-4911-9454-6de69751f53b,2026-10-14,13:13:57,Wednesday,2,13
2,BTS,The Most Beautiful Moment in Life: Young Forever,2026-10-14 13:10:11-03:00,House Of Cards (Full Length Edition),0d79fe8e-ba27-4859-bb8c-2f255f346853,2026-10-14,13:10:11,Wednesday,2,13
3,BTS,ARIRANG,2026-10-14 13:06:53-03:00,Please,0d79fe8e-ba27-4859-bb8c-2f255f346853,2026-10-14,13:06:53,Wednesday,2,13
4,BTS,Skool Luv Affair,2026-10-14 12:48:52-03:00,JUMP,0d79fe8e-ba27-4859-bb8c-2f255f346853,2026-10-14,12:48:52,Wednesday,2,12
5,BTS,FAKE LOVE (Rocking Vibe Mix),2026-10-14 12:44:23-03:00,FAKE LOVE - Rocking Vibe Mix,NaN,2026-10-14,12:44:23,Wednesday,2,12
6,RM,mono.,2026-10-14 12:42:07-03:00,moonchild,3be217fb-2b91-4911-9454-6de69751f53b,2026-10-14,12:42:07,Wednesday,2,12
7,BTS,ARIRANG,2026-10-14 12:38:57-03:00,Body to Body,0d79fe8e-ba27-4859-bb8c-2f255f346853,2026-10-14,12:38:57,Wednesday,2,12
8,Taylor Swift,Red (Taylor's Version),2026-10-14 07:45:18-03:00,Sad Beautiful Tragic (Taylor's Version),20244d07-534f-4eff-b4d4-930878889970,2026-10-14,07:45:18,Wednesday,2,7
9,Taylor Swift,THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,2026-10-14 07:42:44-03:00,I Look in People's Windows,20244d07-534f-4eff-b4d4-930878889970,2026-10-14,07:42:44,Wednesday,2,7

In [97]:
df_mb= pd.read_csv('../../data/processed/musicBrainz_transformed.csv')

In [98]:
print(df_lastfm.columns.tolist())

['artist_name', 'album_name', 'scrobble_date', 'music_name', 'artist_mbid', 'date', 'time', 'week_day', 'week_day_id', 'group_hour']

In [99]:
print(df_mb.columns.tolist())

['id', 'type', 'name', 'gender', 'country', 'area.type', 'area.name', 'query_name', 'legal_name', 'music_genre']

In [100]:
# Padroniza os nomes: remove espaços nas pontas e converte para minúsculas
df_lastfm['nome_chave'] = df_lastfm['artist_name'].str.strip().str.lower()
df_mb['nome_chave'] = df_mb['query_name'].str.strip().str.lower()
# padroniza nomes de artistas ex: willow, que no musicBrainz aparecia como WILLOW

# Mantém todas as linhas da tabela Last.fm
df_final = df_lastfm.merge(
    df_mb,
    on='nome_chave',
    how='left'
)

# Remove a coluna auxiliar do resultado
df_final = df_final.drop(columns=['nome_chave'])
# query_name é a "ponte" garantida entre as duas tabelas, porque ela nasceu do mesmo valor original.

In [101]:
# df_final = df_lastfm.merge(df_mb, left_on='artist_name', right_on='name', how='left')
# #last_fm -> tabela base
# #left_on= tabela da esquerda e chave de comparação
# #right_on= tabela da direita + chave de comparação
# #how=left -> mantem todas as linhas da tabela principal mesmo que não haja relação com a outra tabela

In [102]:
df_final.head(50)

,artist_name,album_name,scrobble_date,music_name,artist_mbid,date,time,week_day,week_day_id,group_hour,id,type,name,gender,country,area.type,area.name,query_name,legal_name,music_genre
0,BTS,The Most Beautiful Moment in Life: Young Forever,2026-10-14 13:17:12-03:00,Converse High,0d79fe8e-ba27-4859-bb8c-2f255f346853,2026-10-14,13:17:12,Wednesday,2,13,0d79fe8e-ba27-4859-bb8c-2f255f346853,Group,BTS,unregistered,KR,Country,South Korea,BTS,unregistered,k-pop
1,RM,Indigo,2026-10-14 13:13:57-03:00,No.2 (with parkjiyoon),3be217fb-2b91-4911-9454-6de69751f53b,2026-10-14,13:13:57,Wednesday,2,13,58f1e354-ecbc-4fd3-aa25-97eb1d9bd8b9,Person,RM,male,KR,Country,South Korea,RM,Nam-joon Kim,pop
2,BTS,The Most Beautiful Moment in Life: Young Forever,2026-10-14 13:10:11-03:00,House Of Cards (Full Length Edition),0d79fe8e-ba27-4859-bb8c-2f255f346853,2026-10-14,13:10:11,Wednesday,2,13,0d79fe8e-ba27-4859-bb8c-2f255f346853,Group,BTS,unregistered,KR,Country,South Korea,BTS,unregistered,k-pop
3,BTS,ARIRANG,2026-10-14 13:06:53-03:00,Please,0d79fe8e-ba27-4859-bb8c-2f255f346853,2026-10-14,13:06:53,Wednesday,2,13,0d79fe8e-ba27-4859-bb8c-2f255f346853,Group,BTS,unregistered,KR,Country,South Korea,BTS,unregistered,k-pop
4,BTS,Skool Luv Affair,2026-10-14 12:48:52-03:00,JUMP,0d79fe8e-ba27-4859-bb8c-2f255f346853,2026-10-14,12:48:52,Wednesday,2,12,0d79fe8e-ba27-4859-bb8c-2f255f346853,Group,BTS,unregistered,KR,Country,South Korea,BTS,unregistered,k-pop
5,BTS,FAKE LOVE (Rocking Vibe Mix),2026-10-14 12:44:23-03:00,FAKE LOVE - Rocking Vibe Mix,NaN,2026-10-14,12:44:23,Wednesday,2,12,0d79fe8e-ba27-4859-bb8c-2f255f346853,Group,BTS,unregistered,KR,Country,South Korea,BTS,unregistered,k-pop
6,RM,mono.,2026-10-14 12:42:07-03:00,moonchild,3be217fb-2b91-4911-9454-6de69751f53b,2026-10-14,12:42:07,Wednesday,2,12,58f1e354-ecbc-4fd3-aa25-97eb1d9bd8b9,Person,RM,male,KR,Country,South Korea,RM,Nam-joon Kim,pop
7,BTS,ARIRANG,2026-10-14 12:38:57-03:00,Body to Body,0d79fe8e-ba27-4859-bb8c-2f255f346853,2026-10-14,12:38:57,Wednesday,2,12,0d79fe8e-ba27-4859-bb8c-2f255f346853,Group,BTS,unregistered,KR,Country,South Korea,BTS,unregistered,k-pop
8,Taylor Swift,Red (Taylor's Version),2026-10-14 07:45:18-03:00,Sad Beautiful Tragic (Taylor's Version),20244d07-534f-4eff-b4d4-930878889970,2026-10-14,07:45:18,Wednesday,2,7,20244d07-534f-4eff-b4d4-930878889970,Person,Taylor Swift,female,US,Country,United States,Taylor Swift,Taylor Alison Swift,pop
9,Taylor Swift,THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,2026-10-14 07:42:44-03:00,I Look in People's Windows,20244d07-534f-4eff-b4d4-930878889970,2026-10-14,07:42:44,Wednesday,2,7,20244d07-534f-4eff-b4d4-930878889970,Person,Taylor Swift,female,US,Country,United States,Taylor Swift,Taylor Alison Swift,pop
10,Olivia Rodrigo,Serena Joy,2026-10-14 07:39:19-03:00,serena joy,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-14,07:39:19,Wednesday,2,7,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Person,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,Olivia Isabel Rodrigo,pop
11,Taylor Swift,folklore,2026-10-14 07:36:04-03:00,this is me trying,20244d07-534f-4eff-b4d4-930878889970,2026-10-14,07:36:04,Wednesday,2,7,20244d07-534f-4eff-b4d4-930878889970,Person,Taylor Swift,female,US,Country,United States,Taylor Swift,Taylor Alison Swift,pop
12,Olivia Rodrigo,All I Want (Love That Lasts Mix),2026-10-14 07:33:02-03:00,All I Want - Love That Lasts Mix,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-14,07:33:02,Wednesday,2,7,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Person,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,Olivia Isabel Rodrigo,pop
13,Olivia Rodrigo,The Hunger Games: The Ballad of Songbirds & Sn...,2026-10-14 07:29:36-03:00,Can’t Catch Me Now - from The Hunger Games: Th...,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-14,07:29:36,Wednesday,2,7,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Person,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,Olivia Isabel Rodrigo,pop
14,Clairo,Charm,2026-10-14 07:25:56-03:00,Add Up My Love,d786f59b-1836-4ddb-8393-ab753edbe984,2026-10-14,07:25:56,Wednesday,2,7,d786f59b-1836-4ddb-8393-ab753edbe984,Person,Clairo,female,US,Country,United States,Clairo,Claire Elizabeth Cottrill,bedroom pop
15,Olivia Rodrigo,you seem pretty sad for a girl so in love,2026-10-14 07:22:42-03:00,less,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-14,07:22:42,Wednesday,2,7,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Person,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,Olivia Isabel Rodrigo,pop
16,Troye Sivan,Spotify Singles,2026-10-14 07:19:00-03:00,Bloom - Recorded At Spotify Studios NYC,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-14,07:19:00,Wednesday,2,7,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,Person,Troye Sivan,male,AU,Country,Australia,Troye Sivan,Troye Sivan Mellet,pop
17,Taylor Swift,Red (Taylor's Version),2026-10-14 07:08:46-03:00,All Too Well (10 Minute Version) (Taylor's Ver...,20244d07-534f-4eff-b4d4-930878889970,2026-10-14,07:08:46,Wednesday,2,7,20244d07-534f-4eff-b4d4-930878889970,Person,Taylor Swift,female,US,Country,United States,Taylor Swift,Taylor Alison Swift,pop
18,Olivia Rodrigo,SOUR,2026-10-14 07:05:16-03:00,hope ur ok,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-14,07:05:16,Wednesday,2,7,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Person,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,Olivia Isabel Rodrigo,pop
19,Olivia Rodrigo,you seem pretty sad for a girl so in love,2026-10-14 07:01:16-03:00,purple,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-14,07:01:16,Wednesday,2,7,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Person,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,Olivia Isabel Rodrigo,pop
20,Taylor Swift,1989 (Taylor's Version),2026-10-14 06:58:15-03:00,"""Slut!"" (Taylor's Version) (From the Vault)",20244d07-534f-4eff-b4d4-930878889970,2026-10-14,06:58:15,Wednesday,2,6,20244d07-534f-4eff-b4d4-930878889970,Person,Taylor Swift,female,US,Country,United States,Taylor Swift,Taylor Alison Swift,pop
21,Taylor Swift,THE TORTURED POETS DEPARTMENT,2026-10-14 06:53:51-03:00,"So Long, London",20244d07-534f-4eff-b4d4-930878889970,2026-10-14,06:53:51,Wednesday,2,6,20244d07-534f-4eff-b4d4-930878889970,Person,Taylor Swift,female,US,Country,United States,Taylor Swift,Taylor Alison Swift,pop
22,Olivia Rodrigo,you seem pretty sad for a girl so in love,2026-10-14 06:50:08-03:00,honeybee,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-14,06:50:08,Wednesday,2,6,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Person,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,Olivia Isabel Rodrigo,pop
23,Phoebe Bridgers,"Lost Ark Studio Compilation, Vol. 8",2026-10-14 06:43:01-03:00,Waiting Room,96855c21-b832-4366-ba12-0d2330c36a86,2026-10-14,06:43:01,Wednesday,2,6,96855c21-b832-4366-ba12-0d2330c36a86,Person,Phoebe Bridgers,female,US,Country,United States,Phoebe Bridgers,unregistered,singer-songwriter
24,George Michael,Ladies & Gentlemen,2026-10-14 06:35:46-03:00,Cowboys And Angels - 2010 Remastered Version,ccb8f30e-4d71-40c4-8b1d-846dafe73e2c,2026-10-14,06:35:46,Wednesday,2,6,ccb8f30e-4d71-40c4-8b1d-846dafe73e2c,Person,George Michael,male,GB,Country,United Kingdom,George Michael,Georgios Kyriacos Panayiotou,pop
25,George Michael,Ladies & Gentlemen,2026-10-12 23:45:20-03:00,Cowboys And Angels - 2010 Remastered Version,ccb8f30e-4d71-40c4-8b1d-846dafe73e2c,2026-10-12,23:45:20,Monday,0,23,ccb8f30e-4d71-40c4-8b1d-846dafe73e2c,Person,George Michael,male,GB,Country,United Kingdom,George Michael,Georgios Kyriacos Panayiotou,pop
26,Tinashe,POPSTAR,2026-10-12 19:54:06-03:00,I’d Rather Be Alone,396a9525-0994-4542-b480-c4587feeb476,2026-10-12,19:54:06,Monday,0,19,396a9525-0994-4542-b480-c4587feeb476,Person,Tinashe,female,US,Country,United States,Tinashe,Tinashe Jorgenson Kachingwe,pop
27,Madison Beer,Showed Me (How I Fell in Love with You),2026-10-12 14:51:36-03:00,Showed Me (How I Fell in Love with You),749ef494-8518-4b49-b685-63d8e728d25c,2026-10-12,14:51:36,Monday,0,14,749ef494-8518-4b49-b685-63d8e728d25c,Person,Madison Beer,female,US,Country,United States,Madison Beer,Madison Elle Beer,pop
28,Katy Perry,Teenage Dream,2026-10-12 14:47:48-03:00,Teenage Dream,122d63fc-8671-43e4-9752-34e846d62a9c,2026-10-12,14:47:48,Monday,0,14,122d63fc-8671-43e4-9752-34e846d62a9c,Person,Katy Perry,female,US,Country,United States,Katy Perry,Katheryn Elizabeth Hudson,pop
29,Sufjan Stevens,Mystery of Love,2026-10-12 14:43:17-03:00,Mystery of Love,01d3c51b-9b98-418a-8d8e-37f6fab59d8c,2026-10-12,14:43:17,Monday,0,14,01d3c51b-9b98-418a-8d8e-37f6fab59d8c,Person,Sufjan Stevens,male,US,Country,United States,Sufjan Stevens,unregistered,indie folk
30,Demi Lovato,Unbroken,2026-10-12 14:39:52-03:00,Give Your Heart a Break,faf4cefb-036c-4c88-b93a-5b03dd0a0e6b,2026-10-12,14:39:52,Monday,0,14,faf4cefb-036c-4c88-b93a-5b03dd0a0e6b,Person,Demi Lovato,non-binary,US,Country,United States,Demi Lovato,Demetria Devonne Lovato,pop
31,Rihanna,Rated R,2026-10-12 14:36:21-03:00,Te Amo,73e5e69d-3554-40d8-8516-00cb38737a1c,2026-10-12,14:36:21,Monday,0,14,73e5e69d-3554-40d8-8516-00cb38737a1c,Person,Rihanna,female,US,Country,United States,Rihanna,Robyn Rihanna Fenty,pop
32,Sabrina Carpenter,Honeymoon Fades,2026-10-12 14:33:05-03:00,Honeymoon Fades,1882fe91-cdd9-49c9-9956-8e06a3810bd4,2026-10-12,14:33:05,Monday,0,14,1882fe91-cdd9-49c9-9956-8e06a3810bd4,Person,Sabrina Carpenter,female,US,Country,United States,Sabrina Carpenter,Sabrina Annlynn Carpenter,pop
33,Kali Uchis,Sin Miedo (del Amor y Otros Demonios) ∞,2026-10-12 14:30:24-03:00,telepatía,d0c7656d-8169-4f77-9dbe-b8f24e40105d,2026-10-12,14:30:24,Monday,0,14,d0c7656d-8169-4f77-9dbe-b8f24e40105d,Person,Kali Uchis,female,US,Country,United States,Kali Uchis,Karly-Marina Loaiza,neo soul
34,Tame Impala,Currents,2026-10-12 14:26:29-03:00,The Less I Know the Better,63aa26c3-d59b-4da4-84ac-716b54f1ef4d,2026-10-12,14:26:29,Monday,0,14,63aa26c3-d59b-4da4-84ac-716b54f1ef4d,Person,Tame Impala,male,AU,Country,Australia,Tame Impala,unregistered,psychedelic rock
35,Tame Impala,The Slow Rush,2026-10-12 14:22:30-03:00,Borderline,63aa26c3-d59b-4da4-84ac-716b54f1ef4d,2026-10-12,14:22:30,Monday,0,14,63aa26c3-d59b-4da4-84ac-716b54f1ef4d,Person,Tame Impala,male,AU,Country,Australia,Tame Impala,unregistered,psychedelic rock
36,a-ha,Lifelines,2026-10-12 14:17:59-03:00,Lifelines - 2019 Remaster,NaN,2026-10-12,14:17:59,Monday,0,14,7364dea6-ca9a-48e3-be01-b44ad0d19897,Group,a‐ha,unregistered,NO,Country,Norway,a-ha,unregistered,new wave
37,Tori Kelly,Foreword,2026-10-12 14:14:39-03:00,Paper Hearts,e4b87494-a5eb-439d-b3bf-5f1b46d4dc6b,2026-10-12,14:14:39,Monday,0,14,e4b87494-a5eb-439d-b3bf-5f1b46d4dc6b,Person,Tori Kelly,female,US,Country,United States,Tori Kelly,Victoria Loren Kelly,soul
38,Lizzy McAlpine,five seconds flat,2026-10-12 14:11:21-03:00,ceilings,ee0b11de-0c8a-4267-9886-198f4579e1db,2026-10-12,14:11:21,Monday,0,14,ee0b11de-0c8a-4267-9886-198f4579e1db,Person,Lizzy McAlpine,female,unregistered,City,Philadelphia,Lizzy McAlpine,Elizabeth Catherine McAlpine,singer-songwriter
39,The Cranberries,"Everybody Else Is Doing It, So Why Can't We?",2026-10-12 14:06:31-03:00,Linger - Remastered 2026,c98d40fd-f6cf-4b26-883e-eaa515ee2851,2026-10-12,14:06:31,Monday,0,14,c98d40fd-f6cf-4b26-883e-eaa515ee2851,Group,The Cranberries,unregistered,IE,Country,Ireland,The Cranberries,unregistered,alternative rock
40,Lady Gaga,The Fame,2026-10-12 14:03:03-03:00,Paparazzi,650e7db6-b795-4eb5-a702-5ea2fc46c848,2026-10-12,14:03:03,Monday,0,14,650e7db6-b795-4eb5-a702-5ea2fc46c848,Person,Lady Gaga,female,US,Country,United States,Lady Gaga,Stefani Joanne Angelina Germanotta,pop
41,Sabrina Carpenter,emails i can’t send fwd:,2026-10-12 14:00:11-03:00,Already Over,1882fe91-cdd9-49c9-9956-8e06a3810bd4,2026-10-12,14:00:11,Monday,0,14,1882fe91-cdd9-49c9-9956-8e06a3810bd4,Person,Sabrina Carpenter,female,US,Country,United States,Sabrina Carpenter,Sabrina Annlynn Carpenter,pop
42,Troye Sivan,Rush,2026-10-12 13:57:34-03:00,Rush,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-12,13:57:34,Monday,0,13,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,Person,Troye Sivan,male,AU,Country,Australia,Troye Sivan,Troye Sivan Mellet,pop
43,Laufey,Bewitched,2026-10-12 13:54:22-03:00,While You Were Sleeping,21a89505-10a9-4ac0-8388-833bc07b9f86,2026-10-12,13:54:22,Monday,0,13,21a89505-10a9-4ac0-8388-833bc07b9f86,Person,Laufey,female,IS,Country,Iceland,Laufey,Laufey Lín Bing Jónsdóttir,jazz pop
44,Sabrina Carpenter,emails i can't send,2026-10-12 13:51:00-03:00,Tornado Warnings,1882fe91-cdd9-49c9-9956-8e06a3810bd4,2026-10-12,13:51:00,Monday,0,13,1882fe91-cdd9-49c9-9956-8e06a3810bd4,Person,Sabrina Carpenter,female,US,Country,United States,Sabrina Carpenter,Sabrina Annlynn Carpenter,pop
45,Ellie Goulding,Fifty Shades Freed (Original Motion Picture So...,2026-10-12 13:46:43-03:00,Love Me Like You Do,33ca19f4-18c8-4411-98df-ac23890ce9f5,2026-10-12,13:46:43,Monday,0,13,33ca19f4-18c8-4411-98df-ac23890ce9f5,Person,Ellie Goulding,female,GB,Country,United Kingdom,Ellie Goulding,Elena Jane Goulding,electropop
46,PinkPantheress,Heaven knows,2026-10-12 13:44:05-03:00,Mosquito,7441014f-f8f5-494f-81db-ff166fbc078d,2026-10-12,13:44:05,Monday,0,13,7441014f-f8f5-494f-81db-ff166fbc078d,Person,PinkPantheress,female,unregistered,Subdivision,England,PinkPantheress,Victoria Beverley Walker,uk garage
47,Justin Timberlake,The 20/20 Experience (Deluxe Version),2026-10-12 13:35:59-03:00,Mirrors,596ffa74-3d08-44ef-b113-765d43d12738,2026-10-12,13:35:59,Monday,0,13,596ffa74-3d08-44ef-b113-765d43d12738,Person,Justin Timberlake,male,US,Country,United States,Justin Timberlake,Justin Randall Timberlake,pop
48,Niall Horan,Flicker (Deluxe),2026-10-12 13:31:40-03:00,Flicker,55e6074f-ef78-4ec3-8fff-bd1b8cc8c14a,2026-10-12,13:31:40,Monday,0,13,55e6074f-ef78-4ec3-8fff-bd1b8cc8c14a,Person,Niall Horan,male,IE,Country,Ireland,Niall Horan,unregistered,pop
49,Lizzy McAlpine,Angel,2026-10-12 13:26:54-03:00,Over Country,ee0b11de-0c8a-4267-9886-198f4579e1db,2026-10-12,13:26:54,Monday,0,13,ee0b11de-0c8a-4267-9886-198f4579e1db,Person,Lizzy McAlpine,female,unregistered,City,Philadelphia,Lizzy McAlpine,Elizabeth Catherine McAlpine,singer-songwriter

In [103]:
# colunas_mb = [
#     'id', 'type', 'name', 'gender', 'country',
#     'area.type', 'area.name', 'legal_name', 'music_genre'
# ]

# df_final[colunas_mb] = df_final[colunas_mb].fillna('unregistered')

In [104]:
df_final.isna().sum()

artist_name        0
album_name         0
scrobble_date      0
music_name         0
artist_mbid      138
date               0
time               0
week_day           0
week_day_id        0
group_hour         0
id                 0
type              28
name               0
gender             0
country            0
area.type          0
area.name          0
query_name         0
legal_name         0
music_genre        0
dtype: int64

In [105]:
df_final[df_final['artist_mbid'].isna()]

,artist_name,album_name,scrobble_date,music_name,artist_mbid,date,time,week_day,week_day_id,group_hour,id,type,name,gender,country,area.type,area.name,query_name,legal_name,music_genre
5,BTS,FAKE LOVE (Rocking Vibe Mix),2026-10-14 12:44:23-03:00,FAKE LOVE - Rocking Vibe Mix,NaN,2026-10-14,12:44:23,Wednesday,2,12,0d79fe8e-ba27-4859-bb8c-2f255f346853,Group,BTS,unregistered,KR,Country,South Korea,BTS,unregistered,k-pop
36,a-ha,Lifelines,2026-10-12 14:17:59-03:00,Lifelines - 2019 Remaster,NaN,2026-10-12,14:17:59,Monday,0,14,7364dea6-ca9a-48e3-be01-b44ad0d19897,Group,a‐ha,unregistered,NO,Country,Norway,a-ha,unregistered,new wave
77,Frank Sinatra,Nothing But The Best (2008 Remastered),2026-10-12 11:29:39-03:00,My Way - 2008 Remastered,NaN,2026-10-12,11:29:39,Monday,0,11,197450cd-0124-4164-b723-3c22dd16494d,Person,Frank Sinatra,male,US,Country,United States,Frank Sinatra,Francis Albert Sinatra,jazz
85,Jennie,FALLEN ANGEL,2026-10-12 11:01:17-03:00,Fallen Angel,NaN,2026-10-12,11:01:17,Monday,0,11,779351de-0da5-4943-928b-495a3c40e8c0,Person,JENNIE,female,KR,Country,South Korea,Jennie,김제니,k-pop
93,Jorge Vercillo,Jorge Vercilo Ao Vivo,2026-10-12 10:32:10-03:00,Melhor Lugar - Ao Vivo No Rio De Janeiro / 2006,NaN,2026-10-12,10:32:10,Monday,0,10,9eb42a57-60f8-4093-a45d-1d882bdc7b8c,Person,Jorge Vercillo,male,BR,Country,Brazil,Jorge Vercillo,Jorge Luiz Sant'anna Vercillo,pop
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1290,Jennie,FALLEN ANGEL,2026-09-14 13:32:16-03:00,Fallen Angel,NaN,2026-09-14,13:32:16,Monday,0,13,779351de-0da5-4943-928b-495a3c40e8c0,Person,JENNIE,female,KR,Country,South Korea,Jennie,김제니,k-pop
1292,Kersty,ELECTRONS,2026-09-14 13:25:45-03:00,ELECTRONS,NaN,2026-09-14,13:25:45,Monday,0,13,5925e68f-721d-444e-afe4-32dd019c45c2,NaN,Kersty Ryan,unregistered,unregistered,unregistered,unregistered,Kersty,unregistered,unregistered
1297,Kersty,ELECTRONS,2026-09-12 10:41:22-03:00,ELECTRONS,NaN,2026-09-12,10:41:22,Saturday,5,10,5925e68f-721d-444e-afe4-32dd019c45c2,NaN,Kersty Ryan,unregistered,unregistered,unregistered,unregistered,Kersty,unregistered,unregistered
1322,Miley Cyrus,Can't Be Tamed,2026-09-10 14:08:55-03:00,Who Owns My Heart,NaN,2026-09-10,14:08:55,Thursday,3,14,7e9bd05a-117f-4cce-87bc-e011527a8b18,Person,Miley Cyrus,non-binary,US,Country,United States,Miley Cyrus,Miley Ray Cyrus,pop
1350,Adele,21,2026-09-06 19:20:21-03:00,Lovesong,NaN,2026-09-06,19:20:21,Sunday,6,19,cc2c9c3c-b7bc-4b8b-84d8-4fbd8779e493,Person,Adele,female,GB,Country,United Kingdom,Adele,Adele Adkins,pop

In [106]:
# sem_match = df_final[df_final['id'].isna()]['artist_name'].unique()
# print(sem_match)

In [107]:
df_final['artist_mbid'] = df_final['artist_mbid'].fillna('unregistered')

In [108]:
df_final.isna().sum()

artist_name       0
album_name        0
scrobble_date     0
music_name        0
artist_mbid       0
date              0
time              0
week_day          0
week_day_id       0
group_hour        0
id                0
type             28
name              0
gender            0
country           0
area.type         0
area.name         0
query_name        0
legal_name        0
music_genre       0
dtype: int64

In [109]:
df_final[df_final['query_name'].isna()]['artist_name'].unique()

<StringArray>
[]
Length: 0, dtype: str

In [112]:
df_final[df_final['type'].isna()][['query_name', 'name']].drop_duplicates()

           query_name             name
187   Pequeno Cidadão  Pequeno Cidadão
203            Kersty      Kersty Ryan
293       Flora Matos      Flora Matos
310           O Surto          O Surto
511  Bloco Da Saudade            Bloco
694      Rio Carnaval     Rio Carnaval

In [ ]:
colunas = ['artist_mbid','type', 'name', 'gender', 'country', 'area.type', 'area.name', 'legal_name', 'music_genre']
df_final[colunas] = df_final[colunas].fillna('unregistered')

In [ ]:
df_final.head(4)

,artist_name,album_name,scrobble_date,music_name,artist_mbid,date,time,week_day,week_day_id,group_hour,id,type,name,gender,country,area.type,area.name,query_name,legal_name,music_genre
0,BTS,The Most Beautiful Moment in Life: Young Forever,2026-10-14 13:17:12-03:00,Converse High,0d79fe8e-ba27-4859-bb8c-2f255f346853,2026-10-14,13:17:12,Wednesday,2,13,0d79fe8e-ba27-4859-bb8c-2f255f346853,Group,BTS,unregistered,KR,Country,South Korea,BTS,unregistered,k-pop
1,RM,Indigo,2026-10-14 13:13:57-03:00,No.2 (with parkjiyoon),3be217fb-2b91-4911-9454-6de69751f53b,2026-10-14,13:13:57,Wednesday,2,13,58f1e354-ecbc-4fd3-aa25-97eb1d9bd8b9,Person,RM,male,KR,Country,South Korea,RM,Nam-joon Kim,pop
2,BTS,The Most Beautiful Moment in Life: Young Forever,2026-10-14 13:10:11-03:00,House Of Cards (Full Length Edition),0d79fe8e-ba27-4859-bb8c-2f255f346853,2026-10-14,13:10:11,Wednesday,2,13,0d79fe8e-ba27-4859-bb8c-2f255f346853,Group,BTS,unregistered,KR,Country,South Korea,BTS,unregistered,k-pop
3,BTS,ARIRANG,2026-10-14 13:06:53-03:00,Please,0d79fe8e-ba27-4859-bb8c-2f255f346853,2026-10-14,13:06:53,Wednesday,2,13,0d79fe8e-ba27-4859-bb8c-2f255f346853,Group,BTS,unregistered,KR,Country,South Korea,BTS,unregistered,k-pop

In [ ]:
df_final.isna().sum()

artist_name      0
album_name       0
scrobble_date    0
music_name       0
artist_mbid      0
date             0
time             0
week_day         0
week_day_id      0
group_hour       0
id               0
type             0
name             0
gender           0
country          0
area.type        0
area.name        0
query_name       0
legal_name       0
music_genre      0
dtype: int64