In [139]:
import json
import pandas as pd

In [140]:
dados_artistas = {}

with open("../../data/raw/musicbrainz_data.json", "r", encoding="utf-8") as arquivo:
    dados_artistas = json.load(arquivo)

df_mb = pd.DataFrame.from_dict(dados_artistas, orient="index") 
#ajustando para tratar as chaves externas como as linhas da tabela, não as colunas (padrão)
# index se refere as chaves externas como linhas

df_mb.head(10)

# count mostra quantos outros artistas semelhantes batem com a nossa busca

,created,count,offset,artists
CMAT,2026-09-21T20:54:11.975Z,14,0,[{'id': '2ac533ad-f3ec-4083-a2d4-6f30393414b3'...
Sufjan Stevens,2026-09-21T20:54:13.790Z,1044,0,[{'id': '01d3c51b-9b98-418a-8d8e-37f6fab59d8c'...
Sabrina Carpenter,2026-09-21T20:54:18.346Z,658,0,[{'id': '1882fe91-cdd9-49c9-9956-8e06a3810bd4'...
Banda Amores,2026-09-21T20:54:20.514Z,1772,0,[{'id': 'a8d00992-f534-47c9-ba76-bd668e8ec508'...
Alceu Valença,2026-09-21T20:54:22.708Z,15,0,[{'id': '7a08d4fb-e5c1-4c39-a99b-1908ca2e83b4'...
Tinashe,2026-09-21T20:54:24.812Z,14,0,[{'id': '396a9525-0994-4542-b480-c4587feeb476'...
Zé Ibarra,2026-09-21T20:54:26.898Z,530,0,[{'id': '0b2665a9-14c0-499a-b9fd-46ed09bbf161'...
Olivia Rodrigo,2026-09-21T20:54:28.990Z,1303,0,[{'id': '6925db17-f35e-42f3-a4eb-84ee6bf5d4b0'...
Pabllo Vittar,2026-09-21T20:53:57.262Z,3,0,[{'id': 'd9550ac2-7bcf-4655-a3fe-24922e254a74'...
Lana Del Rey,2026-09-21T20:54:33.200Z,29385,0,[{'id': 'b7539c32-53e7-4908-bda3-81449c367da6'...

In [141]:
df_mb.shape

(103, 4)

In [142]:
df_mb.columns

Index(['created', 'count', 'offset', 'artists'], dtype='str')

In [143]:
df_mb.drop(columns=['created', 'count', 'offset'], inplace=True)

In [144]:
df_mb.head()

                                                             artists
CMAT               [{'id': '2ac533ad-f3ec-4083-a2d4-6f30393414b3'...
Sufjan Stevens     [{'id': '01d3c51b-9b98-418a-8d8e-37f6fab59d8c'...
Sabrina Carpenter  [{'id': '1882fe91-cdd9-49c9-9956-8e06a3810bd4'...
Banda Amores       [{'id': 'a8d00992-f534-47c9-ba76-bd668e8ec508'...
Alceu Valença      [{'id': '7a08d4fb-e5c1-4c39-a99b-1908ca2e83b4'...

In [145]:
df_mb_exploded = df_mb.explode('artists').reset_index(drop=True)
# explode = pega os dicionários aninhados numa lista e transforma em linhas
df_mb_normalizado = pd.json_normalize(df_mb_exploded['artists']).reset_index(drop=True)
#o json_normalize pega esses dícionários e transforma suas prorpiedades em colunas
df_mb_normalizado.head(10)

,id,type,type-id,score,gender-id,name,sort-name,gender,country,isnis,...,ipis,disambiguation,end-area.id,end-area.type,end-area.type-id,end-area.name,end-area.sort-name,end-area.life-span.ended,life-span.end,area.life-span.begin
0,2ac533ad-f3ec-4083-a2d4-6f30393414b3,Person,b6e035f4-3ce9-331c-97df-83397230b0df,100,93452b5a-a947-30c8-934f-6a4056b151c2,CMAT,CMAT,female,IE,[0000000507072282],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,01d3c51b-9b98-418a-8d8e-37f6fab59d8c,Person,b6e035f4-3ce9-331c-97df-83397230b0df,100,36d3d30a-839d-3eda-8cb3-29be4384e4a9,Sufjan Stevens,"Stevens, Sufjan",male,US,[0000000110253464],...,[00441776251],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1882fe91-cdd9-49c9-9956-8e06a3810bd4,Person,b6e035f4-3ce9-331c-97df-83397230b0df,100,93452b5a-a947-30c8-934f-6a4056b151c2,Sabrina Carpenter,"Carpenter, Sabrina",female,US,[0000000440350523],...,[00662307358],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,a8d00992-f534-47c9-ba76-bd668e8ec508,Group,e431f5f6-b5d2-343d-8b36-72607fffb74b,100,NaN,Amores,Amores,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7a08d4fb-e5c1-4c39-a99b-1908ca2e83b4,Person,b6e035f4-3ce9-331c-97df-83397230b0df,100,36d3d30a-839d-3eda-8cb3-29be4384e4a9,Alceu Valença,"Valença, Alceu",male,BR,NaN,...,[00070058302],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,396a9525-0994-4542-b480-c4587feeb476,Person,b6e035f4-3ce9-331c-97df-83397230b0df,100,93452b5a-a947-30c8-934f-6a4056b151c2,Tinashe,Tinashe,female,US,[000000010834165X],...,"[00593900722, 00593900820]",American R&B singer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,0b2665a9-14c0-499a-b9fd-46ed09bbf161,Person,b6e035f4-3ce9-331c-97df-83397230b0df,100,36d3d30a-839d-3eda-8cb3-29be4384e4a9,Zé Ibarra,"Ibarra, Zé",male,NaN,[0000000493736411],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Person,b6e035f4-3ce9-331c-97df-83397230b0df,100,93452b5a-a947-30c8-934f-6a4056b151c2,Olivia Rodrigo,"Rodrigo, Olivia",female,US,[000000047619573X],...,[00387176421],US singer‐songwriter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,d9550ac2-7bcf-4655-a3fe-24922e254a74,Person,b6e035f4-3ce9-331c-97df-83397230b0df,100,b239bbd8-aa84-4f11-8bdb-c4159e730ee5,Pabllo Vittar,"Vittar, Pabllo",non-binary,BR,[0000000466937285],...,[00862259027],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,b7539c32-53e7-4908-bda3-81449c367da6,Person,b6e035f4-3ce9-331c-97df-83397230b0df,100,93452b5a-a947-30c8-934f-6a4056b151c2,Lana Del Rey,"Del Rey, Lana",female,US,"[0000000360454402, 0000000368678910]",...,"[00579892274, 00667129814]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [146]:
df_mb_normalizado.columns

Index(['id', 'type', 'type-id', 'score', 'gender-id', 'name', 'sort-name',
       'gender', 'country', 'isnis', 'aliases', 'tags', 'area.id', 'area.type',
       'area.type-id', 'area.name', 'area.sort-name', 'area.life-span.ended',
       'begin-area.id', 'begin-area.type', 'begin-area.type-id',
       'begin-area.name', 'begin-area.sort-name', 'begin-area.life-span.ended',
       'life-span.begin', 'life-span.ended', 'ipis', 'disambiguation',
       'end-area.id', 'end-area.type', 'end-area.type-id', 'end-area.name',
       'end-area.sort-name', 'end-area.life-span.ended', 'life-span.end',
       'area.life-span.begin'],
      dtype='str')

In [147]:
df_mb_normalizado.drop(columns=['score','type-id', 'gender-id', 'sort-name', 'isnis', 'area.id', 'area.type-id', 'area.sort-name', 
                                'area.life-span.ended', 'begin-area.id', 'begin-area.type', 'begin-area.type-id',
                                'begin-area.name', 'begin-area.sort-name', 'begin-area.life-span.ended',
                                'life-span.begin', 'life-span.ended', 'ipis','disambiguation', 'end-area.id', 'end-area.type', 'end-area.type-id', 'end-area.name',
                                'end-area.sort-name', 'end-area.life-span.ended', 'life-span.end',
                                'area.life-span.begin'], inplace=True)

df_mb_normalizado.head(10)

,id,type,name,gender,country,aliases,tags,area.type,area.name
0,2ac533ad-f3ec-4083-a2d4-6f30393414b3,Person,CMAT,female,IE,"[{'sort-name': 'Thompson, Ciara Mary-Alice', '...","[{'count': 1, 'name': 'pop'}, {'count': 1, 'na...",Country,Ireland
1,01d3c51b-9b98-418a-8d8e-37f6fab59d8c,Person,Sufjan Stevens,male,US,"[{'sort-name': 'Stevens', 'name': 'Stevens', '...","[{'count': 0, 'name': 'alternative rock'}, {'c...",Country,United States
2,1882fe91-cdd9-49c9-9956-8e06a3810bd4,Person,Sabrina Carpenter,female,US,"[{'sort-name': 'Carpenter, Sabrina', 'type-id'...","[{'count': 9, 'name': 'pop'}, {'count': 1, 'na...",Country,United States
3,a8d00992-f534-47c9-ba76-bd668e8ec508,Group,Amores,NaN,NaN,NaN,NaN,NaN,NaN
4,7a08d4fb-e5c1-4c39-a99b-1908ca2e83b4,Person,Alceu Valença,male,BR,"[{'sort-name': 'Valença, Alceu Paiva', 'type-i...","[{'count': 2, 'name': 'pop'}, {'count': 1, 'na...",Country,Brazil
5,396a9525-0994-4542-b480-c4587feeb476,Person,Tinashe,female,US,"[{'sort-name': 'Jorgenson Kachingwe, Tinashe',...","[{'count': 2, 'name': 'pop'}, {'count': 2, 'na...",Country,United States
6,0b2665a9-14c0-499a-b9fd-46ed09bbf161,Person,Zé Ibarra,male,NaN,NaN,NaN,City,Rio de Janeiro
7,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Person,Olivia Rodrigo,female,US,"[{'sort-name': '奥利维亚·罗德里戈', 'type-id': '894afb...","[{'count': 1, 'name': 'rock'}, {'count': 14, '...",Country,United States
8,d9550ac2-7bcf-4655-a3fe-24922e254a74,Person,Pabllo Vittar,non-binary,BR,"[{'sort-name': 'Silva, Phabullo Rodrigues da',...","[{'count': 3, 'name': 'drag queen'}, {'count':...",Country,Brazil
9,b7539c32-53e7-4908-bda3-81449c367da6,Person,Lana Del Rey,female,US,"[{'sort-name': 'Del Rey, Lana', 'type-id': '89...","[{'count': 1, 'name': 'rock'}, {'count': 5, 'n...",Country,United States

In [148]:
df_mb_normalizado['aliases'].head(10)

0    [{'sort-name': 'Thompson, Ciara Mary-Alice', '...
1    [{'sort-name': 'Stevens', 'name': 'Stevens', '...
2    [{'sort-name': 'Carpenter, Sabrina', 'type-id'...
3                                                  NaN
4    [{'sort-name': 'Valença, Alceu Paiva', 'type-i...
5    [{'sort-name': 'Jorgenson Kachingwe, Tinashe',...
6                                                  NaN
7    [{'sort-name': '奥利维亚·罗德里戈', 'type-id': '894afb...
8    [{'sort-name': 'Silva, Phabullo Rodrigues da',...
9    [{'sort-name': 'Del Rey, Lana', 'type-id': '89...
Name: aliases, dtype: object

In [149]:
df_mb_normalizado['legal_name'] = df_mb_normalizado['aliases'].apply(lambda lista: next(
    (a['name'] for a in lista if a.get('type') == 'Legal name'), 'unregistered') if isinstance(lista, list) else 'unregistered'
    )

In [150]:
df_mb_normalizado.head(5)

,id,type,name,gender,country,aliases,tags,area.type,area.name,legal_name
0,2ac533ad-f3ec-4083-a2d4-6f30393414b3,Person,CMAT,female,IE,"[{'sort-name': 'Thompson, Ciara Mary-Alice', '...","[{'count': 1, 'name': 'pop'}, {'count': 1, 'na...",Country,Ireland,Ciara Mary-Alice Thompson
1,01d3c51b-9b98-418a-8d8e-37f6fab59d8c,Person,Sufjan Stevens,male,US,"[{'sort-name': 'Stevens', 'name': 'Stevens', '...","[{'count': 0, 'name': 'alternative rock'}, {'c...",Country,United States,unregistered
2,1882fe91-cdd9-49c9-9956-8e06a3810bd4,Person,Sabrina Carpenter,female,US,"[{'sort-name': 'Carpenter, Sabrina', 'type-id'...","[{'count': 9, 'name': 'pop'}, {'count': 1, 'na...",Country,United States,Sabrina Annlynn Carpenter
3,a8d00992-f534-47c9-ba76-bd668e8ec508,Group,Amores,NaN,NaN,NaN,NaN,NaN,NaN,unregistered
4,7a08d4fb-e5c1-4c39-a99b-1908ca2e83b4,Person,Alceu Valença,male,BR,"[{'sort-name': 'Valença, Alceu Paiva', 'type-i...","[{'count': 2, 'name': 'pop'}, {'count': 1, 'na...",Country,Brazil,Alceu Paiva Valença

In [151]:
# Primeiro método de tratamento de nomes que tentei
# df_mb_normalizado['legal_name'] = df_mb_normalizado['aliases'].str[0].str['name'].fillna('unregistered')
# # tratando dados nulos do nome legal
# # aliases é uma lista de dicionários, com .str consigo acessar cada elemento dentro do dicionário
# # se for NaN, substitui por um texto fixo
df_mb_normalizado.drop(columns=['aliases'], inplace=True)
df_mb_normalizado.head(10)

,id,type,name,gender,country,tags,area.type,area.name,legal_name
0,2ac533ad-f3ec-4083-a2d4-6f30393414b3,Person,CMAT,female,IE,"[{'count': 1, 'name': 'pop'}, {'count': 1, 'na...",Country,Ireland,Ciara Mary-Alice Thompson
1,01d3c51b-9b98-418a-8d8e-37f6fab59d8c,Person,Sufjan Stevens,male,US,"[{'count': 0, 'name': 'alternative rock'}, {'c...",Country,United States,unregistered
2,1882fe91-cdd9-49c9-9956-8e06a3810bd4,Person,Sabrina Carpenter,female,US,"[{'count': 9, 'name': 'pop'}, {'count': 1, 'na...",Country,United States,Sabrina Annlynn Carpenter
3,a8d00992-f534-47c9-ba76-bd668e8ec508,Group,Amores,NaN,NaN,NaN,NaN,NaN,unregistered
4,7a08d4fb-e5c1-4c39-a99b-1908ca2e83b4,Person,Alceu Valença,male,BR,"[{'count': 2, 'name': 'pop'}, {'count': 1, 'na...",Country,Brazil,Alceu Paiva Valença
5,396a9525-0994-4542-b480-c4587feeb476,Person,Tinashe,female,US,"[{'count': 2, 'name': 'pop'}, {'count': 2, 'na...",Country,United States,Tinashe Jorgenson Kachingwe
6,0b2665a9-14c0-499a-b9fd-46ed09bbf161,Person,Zé Ibarra,male,NaN,NaN,City,Rio de Janeiro,unregistered
7,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Person,Olivia Rodrigo,female,US,"[{'count': 1, 'name': 'rock'}, {'count': 14, '...",Country,United States,Olivia Isabel Rodrigo
8,d9550ac2-7bcf-4655-a3fe-24922e254a74,Person,Pabllo Vittar,non-binary,BR,"[{'count': 3, 'name': 'drag queen'}, {'count':...",Country,Brazil,Phabullo Rodrigues da Silva
9,b7539c32-53e7-4908-bda3-81449c367da6,Person,Lana Del Rey,female,US,"[{'count': 1, 'name': 'rock'}, {'count': 5, 'n...",Country,United States,Elizabeth Woolridge Grant

In [152]:
df_mb_normalizado.isna()

,id,type,name,gender,country,tags,area.type,area.name,legal_name
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,True,True,True,True,True,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
98,False,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False
100,False,False,False,False,False,False,False,False,False
101,False,False,False,False,False,False,False,False,False
102,False,False,False,True,False,False,False,False,False

In [153]:
df_mb_normalizado['tags']

0      [{'count': 1, 'name': 'pop'}, {'count': 1, 'na...
1      [{'count': 0, 'name': 'alternative rock'}, {'c...
2      [{'count': 9, 'name': 'pop'}, {'count': 1, 'na...
3                                                    NaN
4      [{'count': 2, 'name': 'pop'}, {'count': 1, 'na...
                             ...
98     [{'count': 1, 'name': 'soul'}, {'count': 1, 'n...
99     [{'count': 1, 'name': 'rap'}, {'count': 2, 'na...
100    [{'count': 2, 'name': 'rock'}, {'count': 5, 'n...
101    [{'count': 1, 'name': 'pop'}, {'count': 1, 'na...
102    [{'count': 21, 'name': 'rock'}, {'count': 21, ...
Name: tags, Length: 103, dtype: object

In [154]:
df_mb_normalizado.isna()

,id,type,name,gender,country,tags,area.type,area.name,legal_name
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,True,True,True,True,True,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
98,False,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False
100,False,False,False,False,False,False,False,False,False
101,False,False,False,False,False,False,False,False,False
102,False,False,False,True,False,False,False,False,False

In [155]:
df_mb_normalizado['music_genre'] = df_mb_normalizado['tags'].str[0].str['name'].fillna('unregisterd')

In [156]:
df_mb_normalizado.head(10)

,id,type,name,gender,country,tags,area.type,area.name,legal_name,music_genre
0,2ac533ad-f3ec-4083-a2d4-6f30393414b3,Person,CMAT,female,IE,"[{'count': 1, 'name': 'pop'}, {'count': 1, 'na...",Country,Ireland,Ciara Mary-Alice Thompson,pop
1,01d3c51b-9b98-418a-8d8e-37f6fab59d8c,Person,Sufjan Stevens,male,US,"[{'count': 0, 'name': 'alternative rock'}, {'c...",Country,United States,unregistered,alternative rock
2,1882fe91-cdd9-49c9-9956-8e06a3810bd4,Person,Sabrina Carpenter,female,US,"[{'count': 9, 'name': 'pop'}, {'count': 1, 'na...",Country,United States,Sabrina Annlynn Carpenter,pop
3,a8d00992-f534-47c9-ba76-bd668e8ec508,Group,Amores,NaN,NaN,NaN,NaN,NaN,unregistered,unregisterd
4,7a08d4fb-e5c1-4c39-a99b-1908ca2e83b4,Person,Alceu Valença,male,BR,"[{'count': 2, 'name': 'pop'}, {'count': 1, 'na...",Country,Brazil,Alceu Paiva Valença,pop
5,396a9525-0994-4542-b480-c4587feeb476,Person,Tinashe,female,US,"[{'count': 2, 'name': 'pop'}, {'count': 2, 'na...",Country,United States,Tinashe Jorgenson Kachingwe,pop
6,0b2665a9-14c0-499a-b9fd-46ed09bbf161,Person,Zé Ibarra,male,NaN,NaN,City,Rio de Janeiro,unregistered,unregisterd
7,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Person,Olivia Rodrigo,female,US,"[{'count': 1, 'name': 'rock'}, {'count': 14, '...",Country,United States,Olivia Isabel Rodrigo,rock
8,d9550ac2-7bcf-4655-a3fe-24922e254a74,Person,Pabllo Vittar,non-binary,BR,"[{'count': 3, 'name': 'drag queen'}, {'count':...",Country,Brazil,Phabullo Rodrigues da Silva,drag queen
9,b7539c32-53e7-4908-bda3-81449c367da6,Person,Lana Del Rey,female,US,"[{'count': 1, 'name': 'rock'}, {'count': 5, 'n...",Country,United States,Elizabeth Woolridge Grant,rock

In [157]:
df_mb_normalizado.drop(columns=['tags'], inplace=True)

In [158]:
# df_mb['music_genre'] = df_mb_normalizado['tags'].apply(lambda lista : max(lista, key= lambda tag: tag['count'])['name'])
# # tags é cada dicionário dentro de lista, que é atualmente uma lista de dicionários
# # usando lambda dentro do max, pegamos o nome de cada gênero que possui maior número de votações

# # count aqui não é a quantidade de vezes que aparece mais, mas que o music Brainz os usuários votam no estilo musical que mais combina com o artista

# df_mb.head(10)

In [159]:
df_mb_normalizado[['gender', 'country','area.type', 'area.name']] = df_mb_normalizado[['gender', 'country','area.type', 'area.name']].fillna('unregistered')

In [160]:
df_mb_normalizado.head(20)

,id,type,name,gender,country,area.type,area.name,legal_name,music_genre
0,2ac533ad-f3ec-4083-a2d4-6f30393414b3,Person,CMAT,female,IE,Country,Ireland,Ciara Mary-Alice Thompson,pop
1,01d3c51b-9b98-418a-8d8e-37f6fab59d8c,Person,Sufjan Stevens,male,US,Country,United States,unregistered,alternative rock
2,1882fe91-cdd9-49c9-9956-8e06a3810bd4,Person,Sabrina Carpenter,female,US,Country,United States,Sabrina Annlynn Carpenter,pop
3,a8d00992-f534-47c9-ba76-bd668e8ec508,Group,Amores,unregistered,unregistered,unregistered,unregistered,unregistered,unregisterd
4,7a08d4fb-e5c1-4c39-a99b-1908ca2e83b4,Person,Alceu Valença,male,BR,Country,Brazil,Alceu Paiva Valença,pop
5,396a9525-0994-4542-b480-c4587feeb476,Person,Tinashe,female,US,Country,United States,Tinashe Jorgenson Kachingwe,pop
6,0b2665a9-14c0-499a-b9fd-46ed09bbf161,Person,Zé Ibarra,male,unregistered,City,Rio de Janeiro,unregistered,unregisterd
7,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Person,Olivia Rodrigo,female,US,Country,United States,Olivia Isabel Rodrigo,rock
8,d9550ac2-7bcf-4655-a3fe-24922e254a74,Person,Pabllo Vittar,non-binary,BR,Country,Brazil,Phabullo Rodrigues da Silva,drag queen
9,b7539c32-53e7-4908-bda3-81449c367da6,Person,Lana Del Rey,female,US,Country,United States,Elizabeth Woolridge Grant,rock
10,4677c3cf-cc38-4e88-9969-bd3d3bf9fda1,Person,Ferrugem,male,BR,Country,Brazil,unregistered,unregisterd
11,985f7e6f-0a7e-4de7-b9ec-a5dac63cb2f7,Person,ZAYN,male,unregistered,Subdivision,England,Zain Javadd Malik,pop
12,b1985fc6-0a34-4159-adfa-2332e6b4beab,Group,Monobloco,unregistered,BR,Country,Brazil,unregistered,samba
13,6bb49d0c-1b4d-4315-a124-c5604363ff2b,Person,Sébastien Driant,male,unregistered,unregistered,unregistered,unregistered,unregisterd
14,cd8086e3-9249-4d5a-a3a0-a20731c98653,Person,Ana Frango Elétrico,non-binary,BR,Country,Brazil,Ana Fainguelernt,mpb
15,94e4af5f-73a3-43da-96bc-49b759bfabdc,Person,Shelly Manne,male,US,Country,United States,Sheldon Manne,jazz
16,f4fdbb4c-e4b7-47a0-b83b-d91bbfcfa387,Person,Ariana Grande,female,US,Country,United States,Ariana Grande-Butera,pop
17,fc63a914-272d-4b95-9221-61adcce6f793,Person,Gal Costa,female,BR,Country,Brazil,Maria da Graça Costa Penna Burgos,mpb
18,6c2a79b8-2b5c-4c2d-b495-6a446811bf9d,Person,Malcolm Todd,male,US,Country,United States,Malcolm Hobert,indie pop
19,502cf908-9921-48bc-bf0e-265c881c0156,Person,sombr,male,US,Country,United States,Shane Michael Boose,indie pop

In [161]:
df_mb_normalizado.isna()

,id,type,name,gender,country,area.type,area.name,legal_name,music_genre
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
98,False,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False
100,False,False,False,False,False,False,False,False,False
101,False,False,False,False,False,False,False,False,False
102,False,False,False,False,False,False,False,False,False

In [162]:
df_mb_normalizado.head(20)

,id,type,name,gender,country,area.type,area.name,legal_name,music_genre
0,2ac533ad-f3ec-4083-a2d4-6f30393414b3,Person,CMAT,female,IE,Country,Ireland,Ciara Mary-Alice Thompson,pop
1,01d3c51b-9b98-418a-8d8e-37f6fab59d8c,Person,Sufjan Stevens,male,US,Country,United States,unregistered,alternative rock
2,1882fe91-cdd9-49c9-9956-8e06a3810bd4,Person,Sabrina Carpenter,female,US,Country,United States,Sabrina Annlynn Carpenter,pop
3,a8d00992-f534-47c9-ba76-bd668e8ec508,Group,Amores,unregistered,unregistered,unregistered,unregistered,unregistered,unregisterd
4,7a08d4fb-e5c1-4c39-a99b-1908ca2e83b4,Person,Alceu Valença,male,BR,Country,Brazil,Alceu Paiva Valença,pop
5,396a9525-0994-4542-b480-c4587feeb476,Person,Tinashe,female,US,Country,United States,Tinashe Jorgenson Kachingwe,pop
6,0b2665a9-14c0-499a-b9fd-46ed09bbf161,Person,Zé Ibarra,male,unregistered,City,Rio de Janeiro,unregistered,unregisterd
7,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Person,Olivia Rodrigo,female,US,Country,United States,Olivia Isabel Rodrigo,rock
8,d9550ac2-7bcf-4655-a3fe-24922e254a74,Person,Pabllo Vittar,non-binary,BR,Country,Brazil,Phabullo Rodrigues da Silva,drag queen
9,b7539c32-53e7-4908-bda3-81449c367da6,Person,Lana Del Rey,female,US,Country,United States,Elizabeth Woolridge Grant,rock
10,4677c3cf-cc38-4e88-9969-bd3d3bf9fda1,Person,Ferrugem,male,BR,Country,Brazil,unregistered,unregisterd
11,985f7e6f-0a7e-4de7-b9ec-a5dac63cb2f7,Person,ZAYN,male,unregistered,Subdivision,England,Zain Javadd Malik,pop
12,b1985fc6-0a34-4159-adfa-2332e6b4beab,Group,Monobloco,unregistered,BR,Country,Brazil,unregistered,samba
13,6bb49d0c-1b4d-4315-a124-c5604363ff2b,Person,Sébastien Driant,male,unregistered,unregistered,unregistered,unregistered,unregisterd
14,cd8086e3-9249-4d5a-a3a0-a20731c98653,Person,Ana Frango Elétrico,non-binary,BR,Country,Brazil,Ana Fainguelernt,mpb
15,94e4af5f-73a3-43da-96bc-49b759bfabdc,Person,Shelly Manne,male,US,Country,United States,Sheldon Manne,jazz
16,f4fdbb4c-e4b7-47a0-b83b-d91bbfcfa387,Person,Ariana Grande,female,US,Country,United States,Ariana Grande-Butera,pop
17,fc63a914-272d-4b95-9221-61adcce6f793,Person,Gal Costa,female,BR,Country,Brazil,Maria da Graça Costa Penna Burgos,mpb
18,6c2a79b8-2b5c-4c2d-b495-6a446811bf9d,Person,Malcolm Todd,male,US,Country,United States,Malcolm Hobert,indie pop
19,502cf908-9921-48bc-bf0e-265c881c0156,Person,sombr,male,US,Country,United States,Shane Michael Boose,indie pop