In [1]:
import json
import pandas as pd

In [2]:
dados_artistas = {}

with open("../../data/raw/musicbrainz_data.json", "r", encoding="utf-8") as arquivo:
    dados_artistas = json.load(arquivo)

df_mb = pd.DataFrame.from_dict(dados_artistas, orient="index") 
#ajustando para tratar as chaves externas como as linhas da tabela, não as colunas (padrão)
# index se refere as chaves externas como linhas -> nomes dos artistas

df_mb.head(10)

# count mostra quantos outros artistas semelhantes batem com a nossa busca

,created,count,offset,artists
CMAT,2026-09-21T20:54:11.975Z,14,0,[{'id': '2ac533ad-f3ec-4083-a2d4-6f30393414b3'...
Sufjan Stevens,2026-09-21T20:54:13.790Z,1044,0,[{'id': '01d3c51b-9b98-418a-8d8e-37f6fab59d8c'...
Sabrina Carpenter,2026-09-21T20:54:18.346Z,658,0,[{'id': '1882fe91-cdd9-49c9-9956-8e06a3810bd4'...
Banda Amores,2026-09-21T20:54:20.514Z,1772,0,[{'id': 'a8d00992-f534-47c9-ba76-bd668e8ec508'...
Alceu Valença,2026-09-21T20:54:22.708Z,15,0,[{'id': '7a08d4fb-e5c1-4c39-a99b-1908ca2e83b4'...
Tinashe,2026-09-21T20:54:24.812Z,14,0,[{'id': '396a9525-0994-4542-b480-c4587feeb476'...
Zé Ibarra,2026-09-21T20:54:26.898Z,530,0,[{'id': '0b2665a9-14c0-499a-b9fd-46ed09bbf161'...
Olivia Rodrigo,2026-09-21T20:54:28.990Z,1303,0,[{'id': '6925db17-f35e-42f3-a4eb-84ee6bf5d4b0'...
Pabllo Vittar,2026-09-21T20:53:57.262Z,3,0,[{'id': 'd9550ac2-7bcf-4655-a3fe-24922e254a74'...
Lana Del Rey,2026-09-21T20:54:33.200Z,29385,0,[{'id': 'b7539c32-53e7-4908-bda3-81449c367da6'...

In [3]:
df_mb.shape

(228, 4)

In [4]:
df_mb.columns

Index(['created', 'count', 'offset', 'artists'], dtype='str')

In [5]:
df_mb.drop(columns=['created', 'count', 'offset'], inplace=True)

In [6]:
df_mb.head()

                                                             artists
CMAT               [{'id': '2ac533ad-f3ec-4083-a2d4-6f30393414b3'...
Sufjan Stevens     [{'id': '01d3c51b-9b98-418a-8d8e-37f6fab59d8c'...
Sabrina Carpenter  [{'id': '1882fe91-cdd9-49c9-9956-8e06a3810bd4'...
Banda Amores       [{'id': 'a8d00992-f534-47c9-ba76-bd668e8ec508'...
Alceu Valença      [{'id': '7a08d4fb-e5c1-4c39-a99b-1908ca2e83b4'...

In [7]:
df_mb['query_name'] = df_mb.index # salvando index para conexão com banco do last fm -> pega o indice estabelecido anteriormente e adiciona a tabela p ligação
df_mb_exploded = df_mb.explode('artists').reset_index(drop=True)
# explode = pega os dicionários aninhados numa lista e transforma em linhas
df_mb_normalizado = pd.json_normalize(df_mb_exploded['artists']).reset_index(drop=True)
#o json_normalize pega esses dícionários e transforma suas prorpiedades em colunas
df_mb_normalizado['query_name'] = df_mb_exploded['query_name'] #passando index para tabela 
# cola no novo df o indice salvo anteriormente

# mantém só as colunas necessárias (aliases e tags ainda são usadas nas próximas células)
colunas_mb = ['id', 'type', 'name', 'gender', 'country', 'area.type',
              'area.name', 'query_name', 'aliases', 'tags']
df_mb_normalizado = df_mb_normalizado.reindex(columns=colunas_mb)

df_mb_normalizado.head(10)

,id,type,name,gender,country,area.type,area.name,query_name,aliases,tags
0,2ac533ad-f3ec-4083-a2d4-6f30393414b3,Person,CMAT,female,IE,Country,Ireland,CMAT,"[{'sort-name': 'Thompson, Ciara Mary-Alice', '...","[{'count': 1, 'name': 'pop'}, {'count': 1, 'na..."
1,01d3c51b-9b98-418a-8d8e-37f6fab59d8c,Person,Sufjan Stevens,male,US,Country,United States,Sufjan Stevens,"[{'sort-name': 'Stevens', 'name': 'Stevens', '...","[{'count': 0, 'name': 'alternative rock'}, {'c..."
2,1882fe91-cdd9-49c9-9956-8e06a3810bd4,Person,Sabrina Carpenter,female,US,Country,United States,Sabrina Carpenter,"[{'sort-name': 'Carpenter, Sabrina', 'type-id'...","[{'count': 9, 'name': 'pop'}, {'count': 1, 'na..."
3,a8d00992-f534-47c9-ba76-bd668e8ec508,Group,Amores,NaN,NaN,NaN,NaN,Banda Amores,NaN,NaN
4,7a08d4fb-e5c1-4c39-a99b-1908ca2e83b4,Person,Alceu Valença,male,BR,Country,Brazil,Alceu Valença,"[{'sort-name': 'Valença, Alceu Paiva', 'type-i...","[{'count': 2, 'name': 'pop'}, {'count': 1, 'na..."
5,396a9525-0994-4542-b480-c4587feeb476,Person,Tinashe,female,US,Country,United States,Tinashe,"[{'sort-name': 'Jorgenson Kachingwe, Tinashe',...","[{'count': 2, 'name': 'pop'}, {'count': 2, 'na..."
6,0b2665a9-14c0-499a-b9fd-46ed09bbf161,Person,Zé Ibarra,male,NaN,City,Rio de Janeiro,Zé Ibarra,NaN,NaN
7,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Person,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,"[{'sort-name': '奥利维亚·罗德里戈', 'type-id': '894afb...","[{'count': 1, 'name': 'rock'}, {'count': 14, '..."
8,d9550ac2-7bcf-4655-a3fe-24922e254a74,Person,Pabllo Vittar,non-binary,BR,Country,Brazil,Pabllo Vittar,"[{'sort-name': 'Silva, Phabullo Rodrigues da',...","[{'count': 3, 'name': 'drag queen'}, {'count':..."
9,b7539c32-53e7-4908-bda3-81449c367da6,Person,Lana Del Rey,female,US,Country,United States,Lana Del Rey,"[{'sort-name': 'Del Rey, Lana', 'type-id': '89...","[{'count': 1, 'name': 'rock'}, {'count': 5, 'n..."

In [8]:
df_mb_normalizado.columns

Index(['id', 'type', 'name', 'gender', 'country', 'area.type', 'area.name',
       'query_name', 'aliases', 'tags'],
      dtype='str')

In [9]:
df_mb_normalizado['aliases'].head(10)

0    [{'sort-name': 'Thompson, Ciara Mary-Alice', '...
1    [{'sort-name': 'Stevens', 'name': 'Stevens', '...
2    [{'sort-name': 'Carpenter, Sabrina', 'type-id'...
3                                                  NaN
4    [{'sort-name': 'Valença, Alceu Paiva', 'type-i...
5    [{'sort-name': 'Jorgenson Kachingwe, Tinashe',...
6                                                  NaN
7    [{'sort-name': '奥利维亚·罗德里戈', 'type-id': '894afb...
8    [{'sort-name': 'Silva, Phabullo Rodrigues da',...
9    [{'sort-name': 'Del Rey, Lana', 'type-id': '89...
Name: aliases, dtype: object

In [10]:
df_mb_normalizado['legal_name'] = df_mb_normalizado['aliases'].apply(lambda lista: next(
    (a['name'] for a in lista if a.get('type') == 'Legal name'), 'unregistered') if isinstance(lista, list) else 'unregistered'
    )

# next(retorna variavel, se encontrar -> for, se não lança esse nome no lugar da exceção)

In [11]:
df_mb_normalizado.head(5)

,id,type,name,gender,country,area.type,area.name,query_name,aliases,tags,legal_name
0,2ac533ad-f3ec-4083-a2d4-6f30393414b3,Person,CMAT,female,IE,Country,Ireland,CMAT,"[{'sort-name': 'Thompson, Ciara Mary-Alice', '...","[{'count': 1, 'name': 'pop'}, {'count': 1, 'na...",Ciara Mary-Alice Thompson
1,01d3c51b-9b98-418a-8d8e-37f6fab59d8c,Person,Sufjan Stevens,male,US,Country,United States,Sufjan Stevens,"[{'sort-name': 'Stevens', 'name': 'Stevens', '...","[{'count': 0, 'name': 'alternative rock'}, {'c...",unregistered
2,1882fe91-cdd9-49c9-9956-8e06a3810bd4,Person,Sabrina Carpenter,female,US,Country,United States,Sabrina Carpenter,"[{'sort-name': 'Carpenter, Sabrina', 'type-id'...","[{'count': 9, 'name': 'pop'}, {'count': 1, 'na...",Sabrina Annlynn Carpenter
3,a8d00992-f534-47c9-ba76-bd668e8ec508,Group,Amores,NaN,NaN,NaN,NaN,Banda Amores,NaN,NaN,unregistered
4,7a08d4fb-e5c1-4c39-a99b-1908ca2e83b4,Person,Alceu Valença,male,BR,Country,Brazil,Alceu Valença,"[{'sort-name': 'Valença, Alceu Paiva', 'type-i...","[{'count': 2, 'name': 'pop'}, {'count': 1, 'na...",Alceu Paiva Valença

In [12]:
# Primeiro método de tratamento de nomes que tentei
# df_mb_normalizado['legal_name'] = df_mb_normalizado['aliases'].str[0].str['name'].fillna('unregistered')
# # tratando dados nulos do nome legal
# # aliases é uma lista de dicionários, com .str consigo acessar cada elemento dentro do dicionário
# # se for NaN, substitui por um texto fixo
df_mb_normalizado.drop(columns=['aliases'], inplace=True)
df_mb_normalizado.head(10)

,id,type,name,gender,country,area.type,area.name,query_name,tags,legal_name
0,2ac533ad-f3ec-4083-a2d4-6f30393414b3,Person,CMAT,female,IE,Country,Ireland,CMAT,"[{'count': 1, 'name': 'pop'}, {'count': 1, 'na...",Ciara Mary-Alice Thompson
1,01d3c51b-9b98-418a-8d8e-37f6fab59d8c,Person,Sufjan Stevens,male,US,Country,United States,Sufjan Stevens,"[{'count': 0, 'name': 'alternative rock'}, {'c...",unregistered
2,1882fe91-cdd9-49c9-9956-8e06a3810bd4,Person,Sabrina Carpenter,female,US,Country,United States,Sabrina Carpenter,"[{'count': 9, 'name': 'pop'}, {'count': 1, 'na...",Sabrina Annlynn Carpenter
3,a8d00992-f534-47c9-ba76-bd668e8ec508,Group,Amores,NaN,NaN,NaN,NaN,Banda Amores,NaN,unregistered
4,7a08d4fb-e5c1-4c39-a99b-1908ca2e83b4,Person,Alceu Valença,male,BR,Country,Brazil,Alceu Valença,"[{'count': 2, 'name': 'pop'}, {'count': 1, 'na...",Alceu Paiva Valença
5,396a9525-0994-4542-b480-c4587feeb476,Person,Tinashe,female,US,Country,United States,Tinashe,"[{'count': 2, 'name': 'pop'}, {'count': 2, 'na...",Tinashe Jorgenson Kachingwe
6,0b2665a9-14c0-499a-b9fd-46ed09bbf161,Person,Zé Ibarra,male,NaN,City,Rio de Janeiro,Zé Ibarra,NaN,unregistered
7,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Person,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,"[{'count': 1, 'name': 'rock'}, {'count': 14, '...",Olivia Isabel Rodrigo
8,d9550ac2-7bcf-4655-a3fe-24922e254a74,Person,Pabllo Vittar,non-binary,BR,Country,Brazil,Pabllo Vittar,"[{'count': 3, 'name': 'drag queen'}, {'count':...",Phabullo Rodrigues da Silva
9,b7539c32-53e7-4908-bda3-81449c367da6,Person,Lana Del Rey,female,US,Country,United States,Lana Del Rey,"[{'count': 1, 'name': 'rock'}, {'count': 5, 'n...",Elizabeth Woolridge Grant

In [13]:
df_mb_normalizado.isna()

,id,type,name,gender,country,area.type,area.name,query_name,tags,legal_name
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,True,True,True,True,False,True,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
223,False,False,False,False,False,False,False,False,False,False
224,False,False,False,True,True,False,False,False,False,False
225,False,False,False,True,False,False,False,False,False,False
226,False,False,False,False,False,False,False,False,False,False
227,False,False,False,False,False,False,False,False,False,False

In [14]:
df_mb_normalizado['gender'] = df_mb_normalizado['gender'].fillna('unregistered')
df_mb_normalizado['area.type'] = df_mb_normalizado['area.type'].fillna('unregistered')
df_mb_normalizado['area.name'] = df_mb_normalizado['area.name'].fillna('unregistered')
df_mb_normalizado['country'] = df_mb_normalizado['country'].fillna('unregistered')
# gênero = tag com mais votos (não a primeira da lista)
def pegar_genero(tags):
    if not isinstance(tags, list) or len(tags) == 0:
        return 'unregistered'
    return max(tags, key=lambda t: t['count'])['name']

df_mb_normalizado['music_genre'] = df_mb_normalizado['tags'].apply(pegar_genero)

In [15]:
df_mb_normalizado['tags']

0      [{'count': 1, 'name': 'pop'}, {'count': 1, 'na...
1      [{'count': 0, 'name': 'alternative rock'}, {'c...
2      [{'count': 9, 'name': 'pop'}, {'count': 1, 'na...
3                                                    NaN
4      [{'count': 2, 'name': 'pop'}, {'count': 1, 'na...
                             ...
223    [{'count': 1, 'name': 'pop'}, {'count': 1, 'na...
224    [{'count': 1, 'name': 'rock'}, {'count': 1, 'n...
225    [{'count': 3, 'name': 'mpb'}, {'count': 0, 'na...
226    [{'count': 2, 'name': 'pop'}, {'count': 1, 'na...
227    [{'count': 1, 'name': 'rock'}, {'count': 14, '...
Name: tags, Length: 228, dtype: object

In [16]:
df_mb_normalizado.isna()

,id,type,name,gender,country,area.type,area.name,query_name,tags,legal_name,music_genre
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,True,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
223,False,False,False,False,False,False,False,False,False,False,False
224,False,False,False,False,False,False,False,False,False,False,False
225,False,False,False,False,False,False,False,False,False,False,False
226,False,False,False,False,False,False,False,False,False,False,False
227,False,False,False,False,False,False,False,False,False,False,False

In [17]:
df_mb_normalizado.head(10)

,id,type,name,gender,country,area.type,area.name,query_name,tags,legal_name,music_genre
0,2ac533ad-f3ec-4083-a2d4-6f30393414b3,Person,CMAT,female,IE,Country,Ireland,CMAT,"[{'count': 1, 'name': 'pop'}, {'count': 1, 'na...",Ciara Mary-Alice Thompson,indie pop
1,01d3c51b-9b98-418a-8d8e-37f6fab59d8c,Person,Sufjan Stevens,male,US,Country,United States,Sufjan Stevens,"[{'count': 0, 'name': 'alternative rock'}, {'c...",unregistered,indie folk
2,1882fe91-cdd9-49c9-9956-8e06a3810bd4,Person,Sabrina Carpenter,female,US,Country,United States,Sabrina Carpenter,"[{'count': 9, 'name': 'pop'}, {'count': 1, 'na...",Sabrina Annlynn Carpenter,pop
3,a8d00992-f534-47c9-ba76-bd668e8ec508,Group,Amores,unregistered,unregistered,unregistered,unregistered,Banda Amores,NaN,unregistered,unregistered
4,7a08d4fb-e5c1-4c39-a99b-1908ca2e83b4,Person,Alceu Valença,male,BR,Country,Brazil,Alceu Valença,"[{'count': 2, 'name': 'pop'}, {'count': 1, 'na...",Alceu Paiva Valença,pop
5,396a9525-0994-4542-b480-c4587feeb476,Person,Tinashe,female,US,Country,United States,Tinashe,"[{'count': 2, 'name': 'pop'}, {'count': 2, 'na...",Tinashe Jorgenson Kachingwe,pop
6,0b2665a9-14c0-499a-b9fd-46ed09bbf161,Person,Zé Ibarra,male,unregistered,City,Rio de Janeiro,Zé Ibarra,NaN,unregistered,unregistered
7,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Person,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,"[{'count': 1, 'name': 'rock'}, {'count': 14, '...",Olivia Isabel Rodrigo,pop
8,d9550ac2-7bcf-4655-a3fe-24922e254a74,Person,Pabllo Vittar,non-binary,BR,Country,Brazil,Pabllo Vittar,"[{'count': 3, 'name': 'drag queen'}, {'count':...",Phabullo Rodrigues da Silva,drag queen
9,b7539c32-53e7-4908-bda3-81449c367da6,Person,Lana Del Rey,female,US,Country,United States,Lana Del Rey,"[{'count': 1, 'name': 'rock'}, {'count': 5, 'n...",Elizabeth Woolridge Grant,indie pop

In [18]:
df_mb_normalizado.drop(columns=['tags'], inplace=True)

In [19]:
# df_mb['music_genre'] = df_mb_normalizado['tags'].apply(lambda lista : max(lista, key= lambda tag: tag['count'])['name'])
# # tags é cada dicionário dentro de lista, que é atualmente uma lista de dicionários
# # usando lambda dentro do max, pegamos o nome de cada gênero que possui maior número de votações

# # count aqui não é a quantidade de vezes que aparece mais, mas que o music Brainz os usuários votam no estilo musical que mais combina com o artista

# df_mb.head(10)

In [20]:
df_mb_normalizado[['gender', 'country','area.type', 'area.name']] = df_mb_normalizado[['gender', 'country','area.type', 'area.name']].fillna('unregistered')

In [21]:
df_mb_normalizado.head(20)

,id,type,name,gender,country,area.type,area.name,query_name,legal_name,music_genre
0,2ac533ad-f3ec-4083-a2d4-6f30393414b3,Person,CMAT,female,IE,Country,Ireland,CMAT,Ciara Mary-Alice Thompson,indie pop
1,01d3c51b-9b98-418a-8d8e-37f6fab59d8c,Person,Sufjan Stevens,male,US,Country,United States,Sufjan Stevens,unregistered,indie folk
2,1882fe91-cdd9-49c9-9956-8e06a3810bd4,Person,Sabrina Carpenter,female,US,Country,United States,Sabrina Carpenter,Sabrina Annlynn Carpenter,pop
3,a8d00992-f534-47c9-ba76-bd668e8ec508,Group,Amores,unregistered,unregistered,unregistered,unregistered,Banda Amores,unregistered,unregistered
4,7a08d4fb-e5c1-4c39-a99b-1908ca2e83b4,Person,Alceu Valença,male,BR,Country,Brazil,Alceu Valença,Alceu Paiva Valença,pop
5,396a9525-0994-4542-b480-c4587feeb476,Person,Tinashe,female,US,Country,United States,Tinashe,Tinashe Jorgenson Kachingwe,pop
6,0b2665a9-14c0-499a-b9fd-46ed09bbf161,Person,Zé Ibarra,male,unregistered,City,Rio de Janeiro,Zé Ibarra,unregistered,unregistered
7,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Person,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,Olivia Isabel Rodrigo,pop
8,d9550ac2-7bcf-4655-a3fe-24922e254a74,Person,Pabllo Vittar,non-binary,BR,Country,Brazil,Pabllo Vittar,Phabullo Rodrigues da Silva,drag queen
9,b7539c32-53e7-4908-bda3-81449c367da6,Person,Lana Del Rey,female,US,Country,United States,Lana Del Rey,Elizabeth Woolridge Grant,indie pop
10,4677c3cf-cc38-4e88-9969-bd3d3bf9fda1,Person,Ferrugem,male,BR,Country,Brazil,Ferrugem,unregistered,unregistered
11,985f7e6f-0a7e-4de7-b9ec-a5dac63cb2f7,Person,ZAYN,male,unregistered,Subdivision,England,ZAYN,Zain Javadd Malik,pop
12,b1985fc6-0a34-4159-adfa-2332e6b4beab,Group,Monobloco,unregistered,BR,Country,Brazil,Monobloco,unregistered,samba
13,6bb49d0c-1b4d-4315-a124-c5604363ff2b,Person,Sébastien Driant,male,unregistered,unregistered,unregistered,Driant,unregistered,unregistered
14,cd8086e3-9249-4d5a-a3a0-a20731c98653,Person,Ana Frango Elétrico,non-binary,BR,Country,Brazil,Ana Frango Elétrico,Ana Fainguelernt,mpb
15,94e4af5f-73a3-43da-96bc-49b759bfabdc,Person,Shelly Manne,male,US,Country,United States,Shelly,Sheldon Manne,jazz
16,f4fdbb4c-e4b7-47a0-b83b-d91bbfcfa387,Person,Ariana Grande,female,US,Country,United States,Ariana Grande,Ariana Grande-Butera,pop
17,fc63a914-272d-4b95-9221-61adcce6f793,Person,Gal Costa,female,BR,Country,Brazil,Gal Costa,Maria da Graça Costa Penna Burgos,mpb
18,6c2a79b8-2b5c-4c2d-b495-6a446811bf9d,Person,Malcolm Todd,male,US,Country,United States,Malcolm Todd,Malcolm Hobert,r&b
19,502cf908-9921-48bc-bf0e-265c881c0156,Person,sombr,male,US,Country,United States,sombr,Shane Michael Boose,indie pop

In [22]:
df_mb_normalizado.isna()

,id,type,name,gender,country,area.type,area.name,query_name,legal_name,music_genre
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
223,False,False,False,False,False,False,False,False,False,False
224,False,False,False,False,False,False,False,False,False,False
225,False,False,False,False,False,False,False,False,False,False
226,False,False,False,False,False,False,False,False,False,False
227,False,False,False,False,False,False,False,False,False,False

In [23]:
df_mb_normalizado.head(30)

,id,type,name,gender,country,area.type,area.name,query_name,legal_name,music_genre
0,2ac533ad-f3ec-4083-a2d4-6f30393414b3,Person,CMAT,female,IE,Country,Ireland,CMAT,Ciara Mary-Alice Thompson,indie pop
1,01d3c51b-9b98-418a-8d8e-37f6fab59d8c,Person,Sufjan Stevens,male,US,Country,United States,Sufjan Stevens,unregistered,indie folk
2,1882fe91-cdd9-49c9-9956-8e06a3810bd4,Person,Sabrina Carpenter,female,US,Country,United States,Sabrina Carpenter,Sabrina Annlynn Carpenter,pop
3,a8d00992-f534-47c9-ba76-bd668e8ec508,Group,Amores,unregistered,unregistered,unregistered,unregistered,Banda Amores,unregistered,unregistered
4,7a08d4fb-e5c1-4c39-a99b-1908ca2e83b4,Person,Alceu Valença,male,BR,Country,Brazil,Alceu Valença,Alceu Paiva Valença,pop
5,396a9525-0994-4542-b480-c4587feeb476,Person,Tinashe,female,US,Country,United States,Tinashe,Tinashe Jorgenson Kachingwe,pop
6,0b2665a9-14c0-499a-b9fd-46ed09bbf161,Person,Zé Ibarra,male,unregistered,City,Rio de Janeiro,Zé Ibarra,unregistered,unregistered
7,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Person,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,Olivia Isabel Rodrigo,pop
8,d9550ac2-7bcf-4655-a3fe-24922e254a74,Person,Pabllo Vittar,non-binary,BR,Country,Brazil,Pabllo Vittar,Phabullo Rodrigues da Silva,drag queen
9,b7539c32-53e7-4908-bda3-81449c367da6,Person,Lana Del Rey,female,US,Country,United States,Lana Del Rey,Elizabeth Woolridge Grant,indie pop
10,4677c3cf-cc38-4e88-9969-bd3d3bf9fda1,Person,Ferrugem,male,BR,Country,Brazil,Ferrugem,unregistered,unregistered
11,985f7e6f-0a7e-4de7-b9ec-a5dac63cb2f7,Person,ZAYN,male,unregistered,Subdivision,England,ZAYN,Zain Javadd Malik,pop
12,b1985fc6-0a34-4159-adfa-2332e6b4beab,Group,Monobloco,unregistered,BR,Country,Brazil,Monobloco,unregistered,samba
13,6bb49d0c-1b4d-4315-a124-c5604363ff2b,Person,Sébastien Driant,male,unregistered,unregistered,unregistered,Driant,unregistered,unregistered
14,cd8086e3-9249-4d5a-a3a0-a20731c98653,Person,Ana Frango Elétrico,non-binary,BR,Country,Brazil,Ana Frango Elétrico,Ana Fainguelernt,mpb
15,94e4af5f-73a3-43da-96bc-49b759bfabdc,Person,Shelly Manne,male,US,Country,United States,Shelly,Sheldon Manne,jazz
16,f4fdbb4c-e4b7-47a0-b83b-d91bbfcfa387,Person,Ariana Grande,female,US,Country,United States,Ariana Grande,Ariana Grande-Butera,pop
17,fc63a914-272d-4b95-9221-61adcce6f793,Person,Gal Costa,female,BR,Country,Brazil,Gal Costa,Maria da Graça Costa Penna Burgos,mpb
18,6c2a79b8-2b5c-4c2d-b495-6a446811bf9d,Person,Malcolm Todd,male,US,Country,United States,Malcolm Todd,Malcolm Hobert,r&b
19,502cf908-9921-48bc-bf0e-265c881c0156,Person,sombr,male,US,Country,United States,sombr,Shane Michael Boose,indie pop
20,f27ec8db-af05-4f36-916e-3d57f91ecf5e,Person,Michael Jackson,male,US,Country,United States,Michael Jackson,Michael Joseph Jackson,pop
21,593d64f5-f8df-4f90-8bd6-ef06986f1e31,Group,Mariasss,unregistered,BR,Country,Brazil,Mariasss,unregistered,unregistered
22,390ff98c-0614-4927-8b94-db7b40a92bbe,Person,Toquinho,male,BR,Country,Brazil,Toquinho,Antônio Pecci Filho,unregistered
23,5925e68f-721d-444e-afe4-32dd019c45c2,NaN,Kersty Ryan,unregistered,unregistered,unregistered,unregistered,Kersty,unregistered,unregistered
24,302bd7b9-d012-4360-897a-93b00c855680,Person,David Guetta,male,FR,Country,France,David Guetta,Pierre David Guetta,house
25,a27207ee-a79e-4887-aa65-e644d2702f5e,Group,Tribalistas,unregistered,BR,Country,Brazil,Tribalistas,unregistered,mpb
26,7eb1ce54-a355-41f9-8d68-e018b096d427,Person,Harry Styles,male,unregistered,Subdivision,England,Harry Styles,Harry Edward Styles,pop
27,29b550f2-04a3-4733-b6f5-4e347fac7e11,Group,Charlie Brown Jr.,unregistered,BR,Country,Brazil,Charlie Brown Jr.,unregistered,alternative rock
28,3b72c1fa-34cd-4b28-b9dc-bf4e15a303df,Group,Katinguelê,unregistered,BR,Country,Brazil,Katinguelê,unregistered,samba
29,39ab1aed-75e0-4140-bd47-540276886b60,Group,Oasis,unregistered,GB,Country,United Kingdom,Oasis,unregistered,britpop

In [24]:
df_mb_normalizado.isna().sum()

id             0
type           6
name           0
gender         0
country        0
area.type      0
area.name      0
query_name     0
legal_name     0
music_genre    0
dtype: int64

In [25]:
df_mb_normalizado.to_csv('../../data/processed/musicBrainz_transformed.csv', index=False)

In [26]:
print(df_mb_normalizado.index[:10])

RangeIndex(start=0, stop=10, step=1)