In [1]:
import json
import pandas as pd

In [2]:
df_lastfm = pd.read_json("../../data/raw/lastfm_scrobbles.json")

# Mantém apenas registros com data
df_lastfm = df_lastfm.dropna(subset=['date']).reset_index(drop=True)

df_lastfm.head(10)

,artist,streamable,image,mbid,album,name,url,date
0,{'mbid': '15741996-1794-42a8-a2c7-1ce3e32d0d75...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",,"{'mbid': '', '#text': 'Duas Cidades'}",Lucro (Descomprimindo),https://www.last.fm/music/BaianaSystem/_/Lucro...,"{'uts': '1792074326', '#text': '15 Oct 2026, 1..."
1,"{'mbid': '', '#text': 'O Surto'}",0,"[{'size': 'small', '#text': 'https://lastfm-im...",05b336dc-2139-3a4c-b55c-00638a3c1dda,{'mbid': '7cbf77e8-e2d4-4c35-80f3-7628d7ddc4e7...,A Cera,https://www.last.fm/music/O+Surto/_/A+Cera,"{'uts': '1792074099', '#text': '15 Oct 2026, 1..."
2,{'mbid': '917e448b-fbed-4062-b563-67566a3b3bb1...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",66d76e8a-ef29-4dba-9cf4-f7a48dd4b0c2,"{'mbid': '', '#text': 'Box Natiruts'}","Sorri, Sou Rei (feat. Claudia Leitte)","https://www.last.fm/music/Natiruts/_/Sorri,+So...","{'uts': '1792073766', '#text': '15 Oct 2026, 1..."
3,{'mbid': '593d64f5-f8df-4f90-8bd6-ef06986f1e31...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",,{'mbid': '51f3caf4-7fc1-4d2d-b6f4-6207ae83ec04...,Flert3,https://www.last.fm/music/Mariasss/_/Flert3,"{'uts': '1792073523', '#text': '15 Oct 2026, 1..."
4,{'mbid': 'c3b70ec4-e13d-47dd-a9a6-94229ed4bc65...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",,"{'mbid': '', '#text': 'DIVERSOS'}",Junto a Mim,https://www.last.fm/music/Lady+Zu/_/Junto+a+Mim,"{'uts': '1792073295', '#text': '15 Oct 2026, 1..."
5,{'mbid': '69d485d1-de5d-4284-b089-74b91336b256...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",,{'mbid': 'a9f575a3-c45b-4a11-8f79-0d0161e2293f...,O vagabundo e a dama,https://www.last.fm/music/Oriente/_/O+vagabund...,"{'uts': '1792072989', '#text': '15 Oct 2026, 1..."
6,"{'mbid': '', '#text': 'Los Hermanos'}",0,"[{'size': 'small', '#text': 'https://lastfm-im...",16d3421d-b9db-3e71-989f-c46233a7ac9f,{'mbid': 'f70805ee-f3f5-4453-a344-eef3ad5f7e85...,Adeus Você,https://www.last.fm/music/Los+Hermanos/_/Adeus...,"{'uts': '1792072810', '#text': '15 Oct 2026, 1..."
7,{'mbid': 'c73d651d-87c9-4c5e-8abb-4ec9c4077241...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",e786c04c-8b2b-3500-a49c-43fff0bf2eef,"{'mbid': '', '#text': 'Musica Para Churrasco, ...",Amiga da Minha Mulher,https://www.last.fm/music/Seu+Jorge/_/Amiga+da...,"{'uts': '1792072561', '#text': '15 Oct 2026, 1..."
8,{'mbid': 'a0e7903d-cde4-4433-8487-8b7b130d715f...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",1e528456-e1b0-4d39-ba41-0719726528f7,{'mbid': '0eff1e8e-1046-4062-a7bd-56adf227d103...,Meu Lugar,https://www.last.fm/music/Arlindo+Cruz/_/Meu+L...,"{'uts': '1792072267', '#text': '15 Oct 2026, 1..."
9,{'mbid': 'f81f19b9-c76e-43ac-8656-bb56071785fb...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",f77e1f00-b2c2-4d6a-988a-b8a33c5586f8,{'mbid': '8d36039e-6eb2-4aff-a5b1-0c08fe691622...,Totalmente Seu,https://www.last.fm/music/Marisa+Monte/_/Total...,"{'uts': '1792072135', '#text': '15 Oct 2026, 1..."

In [3]:
df_lastfm.shape

(1384, 8)

In [4]:
artist_normalizado = pd.json_normalize(df_lastfm['artist'])
album_normalizado = pd.json_normalize(df_lastfm['album'])
data_normalizado = pd.json_normalize(df_lastfm['date'])
df_lastfm['artist_name'] = artist_normalizado['#text']
df_lastfm['album_name'] = album_normalizado['#text']
df_lastfm['scrobble_date'] = data_normalizado['uts'] 
df_lastfm['music_name'] = df_lastfm['name']

# trocando a extração de text para uts -> timestamp unix que contabiliza as horas desde 00:00 1 de janeiro de 1970
df_lastfm['artist_mbid'] = df_lastfm['artist'].str['mbid'] #extraindo ID
df_lastfm.head()

,artist,streamable,image,mbid,album,name,url,date,artist_name,album_name,scrobble_date,music_name,artist_mbid
0,{'mbid': '15741996-1794-42a8-a2c7-1ce3e32d0d75...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",,"{'mbid': '', '#text': 'Duas Cidades'}",Lucro (Descomprimindo),https://www.last.fm/music/BaianaSystem/_/Lucro...,"{'uts': '1792074326', '#text': '15 Oct 2026, 1...",BaianaSystem,Duas Cidades,1792074326,Lucro (Descomprimindo),15741996-1794-42a8-a2c7-1ce3e32d0d75
1,"{'mbid': '', '#text': 'O Surto'}",0,"[{'size': 'small', '#text': 'https://lastfm-im...",05b336dc-2139-3a4c-b55c-00638a3c1dda,{'mbid': '7cbf77e8-e2d4-4c35-80f3-7628d7ddc4e7...,A Cera,https://www.last.fm/music/O+Surto/_/A+Cera,"{'uts': '1792074099', '#text': '15 Oct 2026, 1...",O Surto,Todo Mundo Doido,1792074099,A Cera,
2,{'mbid': '917e448b-fbed-4062-b563-67566a3b3bb1...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",66d76e8a-ef29-4dba-9cf4-f7a48dd4b0c2,"{'mbid': '', '#text': 'Box Natiruts'}","Sorri, Sou Rei (feat. Claudia Leitte)","https://www.last.fm/music/Natiruts/_/Sorri,+So...","{'uts': '1792073766', '#text': '15 Oct 2026, 1...",Natiruts,Box Natiruts,1792073766,"Sorri, Sou Rei (feat. Claudia Leitte)",917e448b-fbed-4062-b563-67566a3b3bb1
3,{'mbid': '593d64f5-f8df-4f90-8bd6-ef06986f1e31...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",,{'mbid': '51f3caf4-7fc1-4d2d-b6f4-6207ae83ec04...,Flert3,https://www.last.fm/music/Mariasss/_/Flert3,"{'uts': '1792073523', '#text': '15 Oct 2026, 1...",Mariasss,Flert3,1792073523,Flert3,593d64f5-f8df-4f90-8bd6-ef06986f1e31
4,{'mbid': 'c3b70ec4-e13d-47dd-a9a6-94229ed4bc65...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",,"{'mbid': '', '#text': 'DIVERSOS'}",Junto a Mim,https://www.last.fm/music/Lady+Zu/_/Junto+a+Mim,"{'uts': '1792073295', '#text': '15 Oct 2026, 1...",Lady Zu,DIVERSOS,1792073295,Junto a Mim,c3b70ec4-e13d-47dd-a9a6-94229ed4bc65

In [5]:
df_lastfm.drop(columns=['name','image','artist','streamable','mbid','date','album','url'], inplace=True)

In [6]:
df_lastfm.head(10)

,artist_name,album_name,scrobble_date,music_name,artist_mbid
0,BaianaSystem,Duas Cidades,1792074326,Lucro (Descomprimindo),15741996-1794-42a8-a2c7-1ce3e32d0d75
1,O Surto,Todo Mundo Doido,1792074099,A Cera,
2,Natiruts,Box Natiruts,1792073766,"Sorri, Sou Rei (feat. Claudia Leitte)",917e448b-fbed-4062-b563-67566a3b3bb1
3,Mariasss,Flert3,1792073523,Flert3,593d64f5-f8df-4f90-8bd6-ef06986f1e31
4,Lady Zu,DIVERSOS,1792073295,Junto a Mim,c3b70ec4-e13d-47dd-a9a6-94229ed4bc65
5,Oriente,Desorientado,1792072989,O vagabundo e a dama,69d485d1-de5d-4284-b089-74b91336b256
6,Los Hermanos,Bloco do Eu Sozinho,1792072810,Adeus Você,
7,Seu Jorge,"Musica Para Churrasco, Vol. 1",1792072561,Amiga da Minha Mulher,c73d651d-87c9-4c5e-8abb-4ec9c4077241
8,Arlindo Cruz,Sambista Perfeito,1792072267,Meu Lugar,a0e7903d-cde4-4433-8487-8b7b130d715f
9,Marisa Monte,Portas,1792072135,Totalmente Seu,f81f19b9-c76e-43ac-8656-bb56071785fb

In [7]:
df_lastfm.columns

Index(['artist_name', 'album_name', 'scrobble_date', 'music_name',
       'artist_mbid'],
      dtype='str')

In [8]:
print(df_lastfm['scrobble_date'].dtype)

str

In [9]:
df_lastfm['scrobble_date'] = df_lastfm['scrobble_date'].astype(int) #unit só lê int, e uts estava como str

In [10]:
#ajustes a serem feitos:
# Converter scrobble_date de texto pra um tipo datetime de verdade
# Ajustar o fuso horário de UTC pra Brasília (UTC-3)

df_lastfm['scrobble_date'] = pd.to_datetime(df_lastfm['scrobble_date'], unit='s', utc=True)
#unit='s' indica que o número indica segundos
#utc=True diz que essa data, assim que convertida, esta marcada como UTC -> padrão global para registrar datas e horas sem considerar fuso-horário
# primeiro passar para padrão (utc), depois passar para fuso de brasília

In [11]:
df_lastfm['scrobble_date'] = df_lastfm['scrobble_date'].dt.tz_convert('America/Sao_Paulo')
df_lastfm.head(10)

,artist_name,album_name,scrobble_date,music_name,artist_mbid
0,BaianaSystem,Duas Cidades,2026-10-15 11:25:26-03:00,Lucro (Descomprimindo),15741996-1794-42a8-a2c7-1ce3e32d0d75
1,O Surto,Todo Mundo Doido,2026-10-15 11:21:39-03:00,A Cera,
2,Natiruts,Box Natiruts,2026-10-15 11:16:06-03:00,"Sorri, Sou Rei (feat. Claudia Leitte)",917e448b-fbed-4062-b563-67566a3b3bb1
3,Mariasss,Flert3,2026-10-15 11:12:03-03:00,Flert3,593d64f5-f8df-4f90-8bd6-ef06986f1e31
4,Lady Zu,DIVERSOS,2026-10-15 11:08:15-03:00,Junto a Mim,c3b70ec4-e13d-47dd-a9a6-94229ed4bc65
5,Oriente,Desorientado,2026-10-15 11:03:09-03:00,O vagabundo e a dama,69d485d1-de5d-4284-b089-74b91336b256
6,Los Hermanos,Bloco do Eu Sozinho,2026-10-15 11:00:10-03:00,Adeus Você,
7,Seu Jorge,"Musica Para Churrasco, Vol. 1",2026-10-15 10:56:01-03:00,Amiga da Minha Mulher,c73d651d-87c9-4c5e-8abb-4ec9c4077241
8,Arlindo Cruz,Sambista Perfeito,2026-10-15 10:51:07-03:00,Meu Lugar,a0e7903d-cde4-4433-8487-8b7b130d715f
9,Marisa Monte,Portas,2026-10-15 10:48:55-03:00,Totalmente Seu,f81f19b9-c76e-43ac-8656-bb56071785fb

In [12]:
df_lastfm['date'] = df_lastfm['scrobble_date'].dt.date
df_lastfm['time'] = df_lastfm['scrobble_date'].dt.time
df_lastfm['week_day'] = df_lastfm['scrobble_date'].dt.day_name()
df_lastfm['week_day_id'] = df_lastfm['scrobble_date'].dt.dayofweek
df_lastfm['group_hour'] = df_lastfm['scrobble_date'].dt.hour
# melhor para fazer agrupamento dos tempos, pois cada tempo é diferente -> mais difícil para análise

df_lastfm.head(10)

#mantém scroble_date para comparações mais fáceis de serem feitas que os dados separados

,artist_name,album_name,scrobble_date,music_name,artist_mbid,date,time,week_day,week_day_id,group_hour
0,BaianaSystem,Duas Cidades,2026-10-15 11:25:26-03:00,Lucro (Descomprimindo),15741996-1794-42a8-a2c7-1ce3e32d0d75,2026-10-15,11:25:26,Thursday,3,11
1,O Surto,Todo Mundo Doido,2026-10-15 11:21:39-03:00,A Cera,,2026-10-15,11:21:39,Thursday,3,11
2,Natiruts,Box Natiruts,2026-10-15 11:16:06-03:00,"Sorri, Sou Rei (feat. Claudia Leitte)",917e448b-fbed-4062-b563-67566a3b3bb1,2026-10-15,11:16:06,Thursday,3,11
3,Mariasss,Flert3,2026-10-15 11:12:03-03:00,Flert3,593d64f5-f8df-4f90-8bd6-ef06986f1e31,2026-10-15,11:12:03,Thursday,3,11
4,Lady Zu,DIVERSOS,2026-10-15 11:08:15-03:00,Junto a Mim,c3b70ec4-e13d-47dd-a9a6-94229ed4bc65,2026-10-15,11:08:15,Thursday,3,11
5,Oriente,Desorientado,2026-10-15 11:03:09-03:00,O vagabundo e a dama,69d485d1-de5d-4284-b089-74b91336b256,2026-10-15,11:03:09,Thursday,3,11
6,Los Hermanos,Bloco do Eu Sozinho,2026-10-15 11:00:10-03:00,Adeus Você,,2026-10-15,11:00:10,Thursday,3,11
7,Seu Jorge,"Musica Para Churrasco, Vol. 1",2026-10-15 10:56:01-03:00,Amiga da Minha Mulher,c73d651d-87c9-4c5e-8abb-4ec9c4077241,2026-10-15,10:56:01,Thursday,3,10
8,Arlindo Cruz,Sambista Perfeito,2026-10-15 10:51:07-03:00,Meu Lugar,a0e7903d-cde4-4433-8487-8b7b130d715f,2026-10-15,10:51:07,Thursday,3,10
9,Marisa Monte,Portas,2026-10-15 10:48:55-03:00,Totalmente Seu,f81f19b9-c76e-43ac-8656-bb56071785fb,2026-10-15,10:48:55,Thursday,3,10

In [13]:
df_lastfm.to_csv('../../data/processed/lastfm_transformed.csv', index=False)