In [1]:
import json
import pandas as pd

In [2]:
df_lastfm = pd.read_json("../../data/raw/lastfm_scrobbles.json")
df_lastfm.head(10)

,artist,streamable,image,mbid,album,name,url,date
0,{'mbid': 'f40856e6-079f-4a0a-916e-9e6a5e04f646...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",d14a2392-c6cc-439c-a576-0a1ad3095660,{'mbid': 'b1032535-694d-45d5-a2ce-cbca1a755400...,Ain't In LA,https://www.last.fm/music/AD%C3%89LA/_/Ain%27t...,"{'uts': '1791456532', '#text': '08 Oct 2026, 1..."
1,"{'mbid': '', '#text': 'Kersty'}",0,"[{'size': 'small', '#text': 'https://lastfm-im...",,"{'mbid': '', '#text': 'ELECTRONS'}",ELECTRONS,https://www.last.fm/music/Kersty/_/ELECTRONS,"{'uts': '1791456326', '#text': '08 Oct 2026, 1..."
2,{'mbid': 'e5712ceb-c37a-4c49-a11c-ccf4e21852d4...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",0a2abc8b-2d9e-4e3f-b83d-75a89fa6f1b6,{'mbid': '292b1501-8b30-4026-81a4-215975885f1d...,Lucky Strike,https://www.last.fm/music/Troye+Sivan/_/Lucky+...,"{'uts': '1791456117', '#text': '08 Oct 2026, 1..."
3,{'mbid': '6925db17-f35e-42f3-a4eb-84ee6bf5d4b0...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",927d1771-3d1b-4cf3-8e94-e1150420f383,{'mbid': 'e142765a-1fb3-4980-90b5-2b39044eb01f...,purple,https://www.last.fm/music/Olivia+Rodrigo/_/purple,"{'uts': '1791455873', '#text': '08 Oct 2026, 1..."
4,{'mbid': 'fc63a914-272d-4b95-9221-61adcce6f793...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",7be064d8-e6ad-3749-ada4-8b9eafdf0a56,"{'mbid': '', '#text': 'Mina D'água do meu Canto'}",Morena Dos Olhos D'agua,https://www.last.fm/music/+noredirect/Gal+Cost...,"{'uts': '1791455655', '#text': '08 Oct 2026, 1..."
5,{'mbid': 'fcc72364-27ff-4c1b-aea3-bc41449003b6...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",,{'mbid': 'fd01eec8-6f12-4e3c-8958-1818bde76c70...,Death of Me,https://www.last.fm/music/Evan/_/Death+of+Me,"{'uts': '1791455468', '#text': '08 Oct 2026, 1..."
6,{'mbid': 'e5712ceb-c37a-4c49-a11c-ccf4e21852d4...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",0f87482f-0f75-4492-a9fb-00d4ad4e3d44,{'mbid': '292b1501-8b30-4026-81a4-215975885f1d...,The Good Side,https://www.last.fm/music/Troye+Sivan/_/The+Go...,"{'uts': '1791455199', '#text': '08 Oct 2026, 1..."
7,{'mbid': '8dfe067c-ae90-472e-80f2-fcee9be4e158...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",43964a41-f4c4-48c3-bf6f-2ee14b2e6c30,{'mbid': '220035b8-0fd7-410e-904e-de009c5aa6f5...,IS THIS LOVE,https://www.last.fm/music/XG/_/IS+THIS+LOVE,"{'uts': '1791455025', '#text': '08 Oct 2026, 1..."
8,{'mbid': 'f40856e6-079f-4a0a-916e-9e6a5e04f646...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",72704e8e-f23d-4a38-9053-498691a4bfa1,{'mbid': 'f363a357-72e8-42d4-bdeb-77b717d73d53...,I'M THE MAN,https://www.last.fm/music/AD%C3%89LA/_/I%27M+T...,"{'uts': '1791454874', '#text': '08 Oct 2026, 1..."
9,{'mbid': 'e5712ceb-c37a-4c49-a11c-ccf4e21852d4...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",186c15f6-2009-40c7-bd1f-c11fd2aa6ff3,{'mbid': '27878688-efa2-40d9-8c17-bf817b0f5232...,IN A DREAM,https://www.last.fm/music/Troye+Sivan/_/IN+A+D...,"{'uts': '1791454644', '#text': '08 Oct 2026, 1..."

In [3]:
df_lastfm.shape

(1154, 8)

In [4]:
artist_normalizado = pd.json_normalize(df_lastfm['artist'])
album_normalizado = pd.json_normalize(df_lastfm['album'])
data_normalizado = pd.json_normalize(df_lastfm['date'])
df_lastfm['artist_name'] = artist_normalizado['#text']
df_lastfm['album_name'] = album_normalizado['#text']
df_lastfm['scrobble_date'] = data_normalizado['uts'] 
df_lastfm['music_name'] = df_lastfm['name']
# trocando a extração de text para uts -> timestamp unix que contabiliza as horas desde 00:00 1 de janeiro de 1970
df_lastfm['artist_mbid'] = df_lastfm['artist'].str['mbid'] #extraindo ID
df_lastfm.head()

,artist,streamable,image,mbid,album,name,url,date,artist_name,album_name,scrobble_date,music_name,artist_mbid
0,{'mbid': 'f40856e6-079f-4a0a-916e-9e6a5e04f646...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",d14a2392-c6cc-439c-a576-0a1ad3095660,{'mbid': 'b1032535-694d-45d5-a2ce-cbca1a755400...,Ain't In LA,https://www.last.fm/music/AD%C3%89LA/_/Ain%27t...,"{'uts': '1791456532', '#text': '08 Oct 2026, 1...",ADÉLA,Ain't In LA,1791456532,Ain't In LA,f40856e6-079f-4a0a-916e-9e6a5e04f646
1,"{'mbid': '', '#text': 'Kersty'}",0,"[{'size': 'small', '#text': 'https://lastfm-im...",,"{'mbid': '', '#text': 'ELECTRONS'}",ELECTRONS,https://www.last.fm/music/Kersty/_/ELECTRONS,"{'uts': '1791456326', '#text': '08 Oct 2026, 1...",Kersty,ELECTRONS,1791456326,ELECTRONS,
2,{'mbid': 'e5712ceb-c37a-4c49-a11c-ccf4e21852d4...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",0a2abc8b-2d9e-4e3f-b83d-75a89fa6f1b6,{'mbid': '292b1501-8b30-4026-81a4-215975885f1d...,Lucky Strike,https://www.last.fm/music/Troye+Sivan/_/Lucky+...,"{'uts': '1791456117', '#text': '08 Oct 2026, 1...",Troye Sivan,Bloom,1791456117,Lucky Strike,e5712ceb-c37a-4c49-a11c-ccf4e21852d4
3,{'mbid': '6925db17-f35e-42f3-a4eb-84ee6bf5d4b0...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",927d1771-3d1b-4cf3-8e94-e1150420f383,{'mbid': 'e142765a-1fb3-4980-90b5-2b39044eb01f...,purple,https://www.last.fm/music/Olivia+Rodrigo/_/purple,"{'uts': '1791455873', '#text': '08 Oct 2026, 1...",Olivia Rodrigo,you seem pretty sad for a girl so in love,1791455873,purple,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0
4,{'mbid': 'fc63a914-272d-4b95-9221-61adcce6f793...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",7be064d8-e6ad-3749-ada4-8b9eafdf0a56,"{'mbid': '', '#text': 'Mina D'água do meu Canto'}",Morena Dos Olhos D'agua,https://www.last.fm/music/+noredirect/Gal+Cost...,"{'uts': '1791455655', '#text': '08 Oct 2026, 1...",Gal Costa,Mina D'água do meu Canto,1791455655,Morena Dos Olhos D'agua,fc63a914-272d-4b95-9221-61adcce6f793

In [5]:
df_lastfm.drop(columns=['name','image','artist','streamable','mbid','date','album','url'], inplace=True)

In [6]:
df_lastfm.head(10)

,artist_name,album_name,scrobble_date,music_name,artist_mbid
0,ADÉLA,Ain't In LA,1791456532,Ain't In LA,f40856e6-079f-4a0a-916e-9e6a5e04f646
1,Kersty,ELECTRONS,1791456326,ELECTRONS,
2,Troye Sivan,Bloom,1791456117,Lucky Strike,e5712ceb-c37a-4c49-a11c-ccf4e21852d4
3,Olivia Rodrigo,you seem pretty sad for a girl so in love,1791455873,purple,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0
4,Gal Costa,Mina D'água do meu Canto,1791455655,Morena Dos Olhos D'agua,fc63a914-272d-4b95-9221-61adcce6f793
5,Evan,DEATH OF ME,1791455468,Death of Me,fcc72364-27ff-4c1b-aea3-bc41449003b6
6,Troye Sivan,Bloom,1791455199,The Good Side,e5712ceb-c37a-4c49-a11c-ccf4e21852d4
7,XG,AWE,1791455025,IS THIS LOVE,8dfe067c-ae90-472e-80f2-fcee9be4e158
8,ADÉLA,PRIMA,1791454874,I'M THE MAN,f40856e6-079f-4a0a-916e-9e6a5e04f646
9,Troye Sivan,In a Dream,1791454644,IN A DREAM,e5712ceb-c37a-4c49-a11c-ccf4e21852d4

In [7]:
df_lastfm.columns

Index(['artist_name', 'album_name', 'scrobble_date', 'music_name',
       'artist_mbid'],
      dtype='str')

In [8]:
print(df_lastfm['scrobble_date'].dtype)

str

In [9]:
df_lastfm['scrobble_date'] = df_lastfm['scrobble_date'].astype(int) #unit só lê int, e uts estava como str

In [10]:
#ajustes a serem feitos:
# Converter scrobble_date de texto pra um tipo datetime de verdade
# Ajustar o fuso horário de UTC pra Brasília (UTC-3)

df_lastfm['scrobble_date'] = pd.to_datetime(df_lastfm['scrobble_date'], unit='s', utc=True)
#unit='s' indica que o número indica segundos
#utc=True diz que essa data, assim que convertida, esta marcada como UTC -> padrão global para registrar datas e horas sem considerar fuso-horário
# primeiro passar para padrão (utc), depois passar para fuso de brasília

In [11]:
df_lastfm['scrobble_date'] = df_lastfm['scrobble_date'].dt.tz_convert('America/Sao_Paulo')
df_lastfm.head(10)

,artist_name,album_name,scrobble_date,music_name,artist_mbid
0,ADÉLA,Ain't In LA,2026-10-08 07:48:52-03:00,Ain't In LA,f40856e6-079f-4a0a-916e-9e6a5e04f646
1,Kersty,ELECTRONS,2026-10-08 07:45:26-03:00,ELECTRONS,
2,Troye Sivan,Bloom,2026-10-08 07:41:57-03:00,Lucky Strike,e5712ceb-c37a-4c49-a11c-ccf4e21852d4
3,Olivia Rodrigo,you seem pretty sad for a girl so in love,2026-10-08 07:37:53-03:00,purple,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0
4,Gal Costa,Mina D'água do meu Canto,2026-10-08 07:34:15-03:00,Morena Dos Olhos D'agua,fc63a914-272d-4b95-9221-61adcce6f793
5,Evan,DEATH OF ME,2026-10-08 07:31:08-03:00,Death of Me,fcc72364-27ff-4c1b-aea3-bc41449003b6
6,Troye Sivan,Bloom,2026-10-08 07:26:39-03:00,The Good Side,e5712ceb-c37a-4c49-a11c-ccf4e21852d4
7,XG,AWE,2026-10-08 07:23:45-03:00,IS THIS LOVE,8dfe067c-ae90-472e-80f2-fcee9be4e158
8,ADÉLA,PRIMA,2026-10-08 07:21:14-03:00,I'M THE MAN,f40856e6-079f-4a0a-916e-9e6a5e04f646
9,Troye Sivan,In a Dream,2026-10-08 07:17:24-03:00,IN A DREAM,e5712ceb-c37a-4c49-a11c-ccf4e21852d4

In [12]:
df_lastfm['date'] = df_lastfm['scrobble_date'].dt.date
df_lastfm['time'] = df_lastfm['scrobble_date'].dt.time
df_lastfm['week_day'] = df_lastfm['scrobble_date'].dt.day_name()
df_lastfm['week_day_id'] = df_lastfm['scrobble_date'].dt.dayofweek
df_lastfm['group_hour'] = df_lastfm['scrobble_date'].dt.hour
# melhor para fazer agrupamento dos tempos, pois cada tempo é diferente -> mais difícil para análise

df_lastfm.head(10)

#mantém scroble_date para comparações mais fáceis de serem feitas que os dados separados

,artist_name,album_name,scrobble_date,music_name,artist_mbid,date,time,week_day,week_day_id,group_hour
0,ADÉLA,Ain't In LA,2026-10-08 07:48:52-03:00,Ain't In LA,f40856e6-079f-4a0a-916e-9e6a5e04f646,2026-10-08,07:48:52,Thursday,3,7
1,Kersty,ELECTRONS,2026-10-08 07:45:26-03:00,ELECTRONS,,2026-10-08,07:45:26,Thursday,3,7
2,Troye Sivan,Bloom,2026-10-08 07:41:57-03:00,Lucky Strike,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-08,07:41:57,Thursday,3,7
3,Olivia Rodrigo,you seem pretty sad for a girl so in love,2026-10-08 07:37:53-03:00,purple,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-08,07:37:53,Thursday,3,7
4,Gal Costa,Mina D'água do meu Canto,2026-10-08 07:34:15-03:00,Morena Dos Olhos D'agua,fc63a914-272d-4b95-9221-61adcce6f793,2026-10-08,07:34:15,Thursday,3,7
5,Evan,DEATH OF ME,2026-10-08 07:31:08-03:00,Death of Me,fcc72364-27ff-4c1b-aea3-bc41449003b6,2026-10-08,07:31:08,Thursday,3,7
6,Troye Sivan,Bloom,2026-10-08 07:26:39-03:00,The Good Side,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-08,07:26:39,Thursday,3,7
7,XG,AWE,2026-10-08 07:23:45-03:00,IS THIS LOVE,8dfe067c-ae90-472e-80f2-fcee9be4e158,2026-10-08,07:23:45,Thursday,3,7
8,ADÉLA,PRIMA,2026-10-08 07:21:14-03:00,I'M THE MAN,f40856e6-079f-4a0a-916e-9e6a5e04f646,2026-10-08,07:21:14,Thursday,3,7
9,Troye Sivan,In a Dream,2026-10-08 07:17:24-03:00,IN A DREAM,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-08,07:17:24,Thursday,3,7

In [13]:
df_lastfm.to_csv('../../data/processed/lastfm_transformed.csv', index=False)