In [16]:
import json
import pandas as pd

In [17]:
df_lastfm = pd.read_json("../../data/raw/lastfm_scrobbles.json")
df_lastfm.head(10)

,artist,streamable,image,mbid,album,name,url,date
0,{'mbid': '610b71d9-fa78-47d6-9073-083922e73840...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",e30259b4-eae1-4449-9079-c1b1c042c718,{'mbid': '8db87670-bb50-40df-afba-0a7dd0e760f1...,Summer Forever,https://www.last.fm/music/Addison+Rae/_/Summer...,"{'uts': '1789635426', '#text': '17 Sep 2026, 0..."
1,{'mbid': '610b71d9-fa78-47d6-9073-083922e73840...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",e30259b4-eae1-4449-9079-c1b1c042c718,{'mbid': '8db87670-bb50-40df-afba-0a7dd0e760f1...,Summer Forever,https://www.last.fm/music/Addison+Rae/_/Summer...,"{'uts': '1789609980', '#text': '17 Sep 2026, 0..."
2,{'mbid': '20244d07-534f-4eff-b4d4-930878889970...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",3177689b-8d6f-45a8-bd05-54108ad61e43,{'mbid': '0854c381-be63-44c7-8695-0878330c4760...,All Too Well (10 Minute Version) (Taylor's Ver...,https://www.last.fm/music/Taylor+Swift/_/All+T...,"{'uts': '1789607385', '#text': '17 Sep 2026, 0..."
3,{'mbid': '20244d07-534f-4eff-b4d4-930878889970...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",3177689b-8d6f-45a8-bd05-54108ad61e43,{'mbid': '0854c381-be63-44c7-8695-0878330c4760...,All Too Well (10 Minute Version) (Taylor's Ver...,https://www.last.fm/music/Taylor+Swift/_/All+T...,"{'uts': '1789601347', '#text': '16 Sep 2026, 2..."
4,{'mbid': '79239441-bfd5-4981-a70c-55c3f15c1287...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",,{'mbid': 'b1587876-ed39-41c0-a19d-8fc1325305b3...,Bring Your Love,https://www.last.fm/music/Madonna/_/Bring+Your...,"{'uts': '1789601124', '#text': '16 Sep 2026, 2..."
5,{'mbid': '1882fe91-cdd9-49c9-9956-8e06a3810bd4...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",a26d6b4d-9019-465f-bd33-33731448ccc6,{'mbid': '8660f5bc-b1a6-4922-be16-89a457ef5609...,My Man on Willpower,https://www.last.fm/music/Sabrina+Carpenter/_/...,"{'uts': '1789600926', '#text': '16 Sep 2026, 2..."
6,{'mbid': '6c2a79b8-2b5c-4c2d-b495-6a446811bf9d...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",8b4a0623-0d13-4361-8e5e-024b9d820fbd,{'mbid': '07fa21fa-235b-4ead-8466-daf8a42899d8...,Earrings,https://www.last.fm/music/Malcolm+Todd/_/Earrings,"{'uts': '1789600774', '#text': '16 Sep 2026, 2..."
7,{'mbid': 'f4fdbb4c-e4b7-47a0-b83b-d91bbfcfa387...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",1d5f8493-e351-404c-aa6f-da5f9ec72715,{'mbid': '8d85167a-5307-47dd-8f2c-eb937051b7bd...,Knew Better Part Two,https://www.last.fm/music/Ariana+Grande/_/Knew...,"{'uts': '1789600609', '#text': '16 Sep 2026, 2..."
8,"{'mbid': '', '#text': 'Troye Sivan'}",0,"[{'size': 'small', '#text': 'https://lastfm-im...",,{'mbid': '27b20242-b752-4071-a84f-67b03f093b3b...,could cry just thinkin about you - Full Version,https://www.last.fm/music/Troye+Sivan/_/could+...,"{'uts': '1789600450', '#text': '16 Sep 2026, 2..."
9,{'mbid': '0d79fe8e-ba27-4859-bb8c-2f255f346853...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",096c01bf-921b-4ca5-897b-ce51cd118e8a,{'mbid': '24bdc37f-7303-4f5e-a5da-0d7752e35867...,Pied Piper,https://www.last.fm/music/BTS/_/Pied+Piper,"{'uts': '1789600204', '#text': '16 Sep 2026, 2..."

In [18]:
df_lastfm.shape

(332, 8)

In [19]:
artist_normalizado = pd.json_normalize(df_lastfm['artist'])
album_normalizado = pd.json_normalize(df_lastfm['album'])
data_normalizado = pd.json_normalize(df_lastfm['date'])
df_lastfm['artist_name'] = artist_normalizado['#text']
df_lastfm['album_name'] = album_normalizado['#text']
df_lastfm['scrobble_date'] = data_normalizado['uts'] 
# trocando a extração de text para uts -> timestamp unix que contabiliza as horas desde 00:00 1 de janeiro de 1970
df_lastfm.head()

,artist,streamable,image,mbid,album,name,url,date,artist_name,album_name,scrobble_date
0,{'mbid': '610b71d9-fa78-47d6-9073-083922e73840...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",e30259b4-eae1-4449-9079-c1b1c042c718,{'mbid': '8db87670-bb50-40df-afba-0a7dd0e760f1...,Summer Forever,https://www.last.fm/music/Addison+Rae/_/Summer...,"{'uts': '1789635426', '#text': '17 Sep 2026, 0...",Addison Rae,Addison,1789635426
1,{'mbid': '610b71d9-fa78-47d6-9073-083922e73840...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",e30259b4-eae1-4449-9079-c1b1c042c718,{'mbid': '8db87670-bb50-40df-afba-0a7dd0e760f1...,Summer Forever,https://www.last.fm/music/Addison+Rae/_/Summer...,"{'uts': '1789609980', '#text': '17 Sep 2026, 0...",Addison Rae,Addison,1789609980
2,{'mbid': '20244d07-534f-4eff-b4d4-930878889970...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",3177689b-8d6f-45a8-bd05-54108ad61e43,{'mbid': '0854c381-be63-44c7-8695-0878330c4760...,All Too Well (10 Minute Version) (Taylor's Ver...,https://www.last.fm/music/Taylor+Swift/_/All+T...,"{'uts': '1789607385', '#text': '17 Sep 2026, 0...",Taylor Swift,Red (Taylor's Version),1789607385
3,{'mbid': '20244d07-534f-4eff-b4d4-930878889970...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",3177689b-8d6f-45a8-bd05-54108ad61e43,{'mbid': '0854c381-be63-44c7-8695-0878330c4760...,All Too Well (10 Minute Version) (Taylor's Ver...,https://www.last.fm/music/Taylor+Swift/_/All+T...,"{'uts': '1789601347', '#text': '16 Sep 2026, 2...",Taylor Swift,Red (Taylor's Version),1789601347
4,{'mbid': '79239441-bfd5-4981-a70c-55c3f15c1287...,0,"[{'size': 'small', '#text': 'https://lastfm-im...",,{'mbid': 'b1587876-ed39-41c0-a19d-8fc1325305b3...,Bring Your Love,https://www.last.fm/music/Madonna/_/Bring+Your...,"{'uts': '1789601124', '#text': '16 Sep 2026, 2...",Madonna,CONFESSIONS II,1789601124

In [20]:
df_lastfm.drop(columns=['artist','streamable','mbid','date','album','url'], inplace=True)

In [21]:
df_lastfm.head(10)

,image,name,artist_name,album_name,scrobble_date
0,"[{'size': 'small', '#text': 'https://lastfm-im...",Summer Forever,Addison Rae,Addison,1789635426
1,"[{'size': 'small', '#text': 'https://lastfm-im...",Summer Forever,Addison Rae,Addison,1789609980
2,"[{'size': 'small', '#text': 'https://lastfm-im...",All Too Well (10 Minute Version) (Taylor's Ver...,Taylor Swift,Red (Taylor's Version),1789607385
3,"[{'size': 'small', '#text': 'https://lastfm-im...",All Too Well (10 Minute Version) (Taylor's Ver...,Taylor Swift,Red (Taylor's Version),1789601347
4,"[{'size': 'small', '#text': 'https://lastfm-im...",Bring Your Love,Madonna,CONFESSIONS II,1789601124
5,"[{'size': 'small', '#text': 'https://lastfm-im...",My Man on Willpower,Sabrina Carpenter,Man’s Best Friend,1789600926
6,"[{'size': 'small', '#text': 'https://lastfm-im...",Earrings,Malcolm Todd,Sweet Boy,1789600774
7,"[{'size': 'small', '#text': 'https://lastfm-im...",Knew Better Part Two,Ariana Grande,Dangerous Woman (Tenth Anniversary Edition),1789600609
8,"[{'size': 'small', '#text': 'https://lastfm-im...",could cry just thinkin about you - Full Version,Troye Sivan,could cry just thinkin about you (Full Version),1789600450
9,"[{'size': 'small', '#text': 'https://lastfm-im...",Pied Piper,BTS,LOVE YOURSELF 承 'Her',1789600204

In [22]:
df_lastfm.columns

Index(['image', 'name', 'artist_name', 'album_name', 'scrobble_date'], dtype='str')

In [23]:
print(df_lastfm['scrobble_date'].dtype)

str

In [24]:
df_lastfm['scrobble_date'] = df_lastfm['scrobble_date'].astype(int) #unit só lê int, e uts estava como str

In [25]:
#ajustes a serem feitos:
# Converter scrobble_date de texto pra um tipo datetime de verdade
# Ajustar o fuso horário de UTC pra Brasília (UTC-3)

df_lastfm['scrobble_date'] = pd.to_datetime(df_lastfm['scrobble_date'], unit='s', utc=True)
#unit='s' indica que o número indica segundos
#utc=True diz que essa data, assim que convertida, esta marcada como UTC -> padrão global para registrar datas e horas sem considerar fuso-horário
# primeiro passar para padrão (utc), depois passar para fuso de brasília

In [27]:
df_lastfm['scrobble_date'] = df_lastfm['scrobble_date'].dt.tz_convert('America/Sao_Paulo')
df_lastfm.head(10)

,image,name,artist_name,album_name,scrobble_date
0,"[{'size': 'small', '#text': 'https://lastfm-im...",Summer Forever,Addison Rae,Addison,2026-09-17 05:57:06-03:00
1,"[{'size': 'small', '#text': 'https://lastfm-im...",Summer Forever,Addison Rae,Addison,2026-09-16 22:53:00-03:00
2,"[{'size': 'small', '#text': 'https://lastfm-im...",All Too Well (10 Minute Version) (Taylor's Ver...,Taylor Swift,Red (Taylor's Version),2026-09-16 22:09:45-03:00
3,"[{'size': 'small', '#text': 'https://lastfm-im...",All Too Well (10 Minute Version) (Taylor's Ver...,Taylor Swift,Red (Taylor's Version),2026-09-16 20:29:07-03:00
4,"[{'size': 'small', '#text': 'https://lastfm-im...",Bring Your Love,Madonna,CONFESSIONS II,2026-09-16 20:25:24-03:00
5,"[{'size': 'small', '#text': 'https://lastfm-im...",My Man on Willpower,Sabrina Carpenter,Man’s Best Friend,2026-09-16 20:22:06-03:00
6,"[{'size': 'small', '#text': 'https://lastfm-im...",Earrings,Malcolm Todd,Sweet Boy,2026-09-16 20:19:34-03:00
7,"[{'size': 'small', '#text': 'https://lastfm-im...",Knew Better Part Two,Ariana Grande,Dangerous Woman (Tenth Anniversary Edition),2026-09-16 20:16:49-03:00
8,"[{'size': 'small', '#text': 'https://lastfm-im...",could cry just thinkin about you - Full Version,Troye Sivan,could cry just thinkin about you (Full Version),2026-09-16 20:14:10-03:00
9,"[{'size': 'small', '#text': 'https://lastfm-im...",Pied Piper,BTS,LOVE YOURSELF 承 'Her',2026-09-16 20:10:04-03:00

In [ ]:
df_lastfm['date'] = df_lastfm['scrobble_date'].dt.date
df_lastfm['time'] = df_lastfm['scrobble_date'].dt.time
df_lastfm['week_day'] = df_lastfm['scrobble_date'].dt.day_name()
df_lastfm['week_day_id'] = df_lastfm['scrobble_date'].dt.dayofweek
df_lastfm['group_hour'] = df_lastfm['scrobble_date'].dt.hour
# melhor para fazer agrupamento dos tempos, pois cada tempo é diferente -> mais difícil para análise

df_lastfm.head(10)

#mantém scroble_date para comparações mais fáceis de serem feitas que os dados separados

,image,name,artist_name,album_name,scrobble_date,date,time,week_day,week_day_id,group_hour
0,"[{'size': 'small', '#text': 'https://lastfm-im...",Summer Forever,Addison Rae,Addison,2026-09-17 05:57:06-03:00,2026-09-17,05:57:06,Thursday,3,5
1,"[{'size': 'small', '#text': 'https://lastfm-im...",Summer Forever,Addison Rae,Addison,2026-09-16 22:53:00-03:00,2026-09-16,22:53:00,Wednesday,2,22
2,"[{'size': 'small', '#text': 'https://lastfm-im...",All Too Well (10 Minute Version) (Taylor's Ver...,Taylor Swift,Red (Taylor's Version),2026-09-16 22:09:45-03:00,2026-09-16,22:09:45,Wednesday,2,22
3,"[{'size': 'small', '#text': 'https://lastfm-im...",All Too Well (10 Minute Version) (Taylor's Ver...,Taylor Swift,Red (Taylor's Version),2026-09-16 20:29:07-03:00,2026-09-16,20:29:07,Wednesday,2,20
4,"[{'size': 'small', '#text': 'https://lastfm-im...",Bring Your Love,Madonna,CONFESSIONS II,2026-09-16 20:25:24-03:00,2026-09-16,20:25:24,Wednesday,2,20
5,"[{'size': 'small', '#text': 'https://lastfm-im...",My Man on Willpower,Sabrina Carpenter,Man’s Best Friend,2026-09-16 20:22:06-03:00,2026-09-16,20:22:06,Wednesday,2,20
6,"[{'size': 'small', '#text': 'https://lastfm-im...",Earrings,Malcolm Todd,Sweet Boy,2026-09-16 20:19:34-03:00,2026-09-16,20:19:34,Wednesday,2,20
7,"[{'size': 'small', '#text': 'https://lastfm-im...",Knew Better Part Two,Ariana Grande,Dangerous Woman (Tenth Anniversary Edition),2026-09-16 20:16:49-03:00,2026-09-16,20:16:49,Wednesday,2,20
8,"[{'size': 'small', '#text': 'https://lastfm-im...",could cry just thinkin about you - Full Version,Troye Sivan,could cry just thinkin about you (Full Version),2026-09-16 20:14:10-03:00,2026-09-16,20:14:10,Wednesday,2,20
9,"[{'size': 'small', '#text': 'https://lastfm-im...",Pied Piper,BTS,LOVE YOURSELF 承 'Her',2026-09-16 20:10:04-03:00,2026-09-16,20:10:04,Wednesday,2,20